Caeden117/ChroMapper

Assets/Plugins/x86.meta, Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/Map/BeatSaberMap.cs, Assets/__Scripts/Map/Events/MapEvent.cs, Assets/__Scripts/Map/Notes/BeatmapChromaNote.cs, Assets/__Scripts/Map/Notes/BeatmapNote.cs, Assets/__Scripts/Map/Obstacles/BeatmapObstacle.cs
modified:   Assets/__Scripts/BeatSaberSong.cs
modified:   Assets/__Scripts/Map/BeatSaberMap.cs
modified:   Assets/__Scripts/Map/Events/MapEvent.cs
modified:   Assets/__Scripts/Map/Notes/BeatmapChromaNote.cs
modified:   Assets/__Scripts/Map/Notes/BeatmapNote.cs
modified:   Assets/__Scripts/Map/Obstacles/BeatmapObstacle.cs
=> Delete pepega toString and set culture to InvariantCulture before writing

Assets/_Graphics/Fonts/Teko-Medium SDF Gold.asset, Assets/_Prefabs/MapEditor/Prefab Materials/obstaclecube.blend.meta, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/BPM Tapper.meta, Assets/__Scripts/MapEditor/UI/BPM Tapper/BPMTapperController.cs, Assets/__Scripts/MapEditor/UI/BPM Tapper/BPMTapperController.cs.meta
Right Shift to toggle the menu
=> Added BPM Tapper

Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
This makes the code, according to my predictions, at least, at the very minimum, I'm pretty positively sure, at least for this exact day I am posting this, nearly, pretty close, to a nice, high value of, a percent, which is, like, approximately, 100% or so, at least I think, not sure actually, perhaps, it could also be, 105% more, in the sense of efficiency, which is the state or quality of being efficient.
=> Replace checks with string.IsNullOrEmpty()

Assets/__Scenes/03_Mapper.unity, Assets/__Scenes/04_Options.unity, Assets/__Scripts/MapEditor/CameraController.cs, Assets/__Scripts/MapEditor/Grid/SoftAttachToNoteGrid.cs, Assets/__Scripts/MapEditor/UI/BPM Tapper/BPMTapperController.cs, Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/Options/OptionsEditorSettings.cs
- Added Camera FOV Slider
- Added a close button to BPM Tapper
- Made light workflow change waveform to the opposite side. Can be toggled.
=> Added a few things.

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/Localization/Localization.asset, Assets/__Scripts/Map/Events/BeatmapEventContainer.cs, Assets/__Scripts/Map/Events/EventAppearanceSO.cs, Assets/__Scripts/Map/Events/MapEvent.cs, Assets/__Scripts/Map/Notes/BeatmapNoteContainer.cs, Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs, Assets/__Scripts/MapEditor/AudioTimeSyncController.cs, Assets/__Scripts/MapEditor/Grid/Collections/BPMChangesContainer.cs, Assets/__Scripts/MapEditor/Grid/PauseToggleLights.cs, Assets/__Scripts/MapEditor/Loading/LoadInitialMap.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BombPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/MapEditor/Mapping/StrobeGenerator.cs, Assets/__Scripts/MapEditor/OSC/OSCMessageSender.cs, Assets/__Scripts/MapEditor/UI/Chroma/ColourPicker.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs, Assets/__Scripts/MapEditor/UI/PastNotesWorker.cs, Assets/__Scripts/UI/MapEditorUI.cs, ProjectSettings/ProjectSettings.asset, ProjectSettings/QualitySettings.asset
- Optimized Past Notes grid
- Optimized Metronome
- Add disclaimer for detected BPM Changes
- Internal optimizations
- Add loading message ideas
- Fix bugs
- Add bugs
=> Development (1/10/20)

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectDeletionAction.cs, Assets/__Scripts/BeatmapActions/Beatmap Actions/NodeEditorUpdatedNodeAction.cs, Assets/__Scripts/BeatmapActions/Beatmap Actions/SelectionDeletedAction.cs, Assets/__Scripts/BeatmapActions/Beatmap Actions/SelectionPastedAction.cs, Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/UI/Placement Controller UI/EventPlacementUI.cs
=> merge dev to 2019.3 for last time

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
=> Fix undo paste action

Assets/__Scripts/BeatmapActions/Beatmap Actions/StrobeGeneratorGenerationAction.cs
=> Fix #63 - StrobeGeneratorGenerationAction still using old collections

Assets/_Graphics/Materials/UI/DiscordPopout.mat, Assets/_Graphics/Materials/UI/OptionsCategory.mat, Assets/_Prefabs/UI/Settings/Options Tab.prefab, Assets/__Scenes/04_Options.unity, Assets/__Scripts/UI/Options/TabButton.cs
I don't know why it has only 5 file changes when I thought you reverted everything...
=> Might have fixed the New Options Menu Materials

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/SongTimelineController.cs
=> Make time display in monospace

Assets/__Scenes/00_FirstBoot.unity, Assets/__Scripts/PluginLoader.meta, Assets/__Scripts/PluginLoader/Attributes.meta, Assets/__Scripts/PluginLoader/Attributes/ExitAttribute.cs, Assets/__Scripts/PluginLoader/Attributes/ExitAttribute.cs.meta, Assets/__Scripts/PluginLoader/Attributes/InitAttribute.cs, Assets/__Scripts/PluginLoader/Attributes/InitAttribute.cs.meta, Assets/__Scripts/PluginLoader/Attributes/PluginAttribute.cs, Assets/__Scripts/PluginLoader/Attributes/PluginAttribute.cs.meta, Assets/__Scripts/PluginLoader/Plugin.cs, Assets/__Scripts/PluginLoader/Plugin.cs.meta, Assets/__Scripts/PluginLoader/PluginLoader.cs, Assets/__Scripts/PluginLoader/PluginLoader.cs.meta, PLUGINS.md
Look at PLUGINS.md to see how it is used, it's very simple at the moment.
=> Added very basic plugin interface and loader

Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs, Assets/__Scripts/UI/SongInfoEditUI.cs
Fix error when info.dat has duplicate characteristics
Fix song info saying changes have been made when numbers have changed less than 0.01, seems to be caused by maps from MMA2 with long floating point values in fields that don't need anything like that amount of precision
Cleaned up duplicated code in zip package
=> Small UI fixes

Assets/__Scripts/Map/BeatmapObjectContainer.cs, Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs, Assets/__Scripts/PluginLoader/Attributes/ObjectLoaded.cs, Assets/__Scripts/PluginLoader/Attributes/ObjectLoaded.cs.meta, Assets/__Scripts/PluginLoader/Plugin.cs, Assets/__Scripts/PluginLoader/PluginLoader.cs
I need this to be public. k? Thanks
Also added some helpers to broadcast events to plugins, only added the one event I needed which is used to decorate blocks as they get loaded. The pretty colours!
=> Plugin API tweaks

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/MapEditor/CameraController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
While holding alt if right clicking instead of left clicking the grid will appear at the position the object is being moved so it's easier to position it in 3d space
Not sure if this should move as much of the elements as it does, but it does the job
Very much doesn't work in 360 maps, but nor does alt + lmb
=> Alt + right click

Assets/HSVPicker/Resources/Shaders/Compute/GenerateSVTexture.compute, Assets/HSVPicker/UI/SVBoxSlider.cs
Compute shader was outputting in gamma space, output values need ^2.2 applied
Also removed passing of texture size
=> Apply color space conversion to color picker

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Makes overwrite paste include rotation events in the note and obstacle group in order to match select between. This PR moves the group related code to utility methods that both select between and overwrite paste use. I put them in SelectionController for now since that's all that uses them.
=> made object groups consistent between overwrite paste and select between

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
Fix node editor disable/enable keybinds
Hide close button when not using keybind as it didn't close it anyway
=> Node editor fixes

Assets/Locales/Mapper Shared Data.asset, Assets/Locales/Mapper_en.asset, Assets/Locales/Mapper_nl.asset, Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BombPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs
Added a "Place Chroma Objects" button in the Chroma drop down
=> Added Chroma Objects Support

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Select between was only looking through loaded containers so large selections would not work. Box select also has a similar issue but this PR does not fix that.
=> fixed selection bug

Assets/Locales/Mapper Shared Data.asset, Assets/Locales/Mapper_en.asset, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/CountersPlusController.cs, Assets/__Scripts/MapEditor/UI/SwingsPerSecond.cs, Assets/__Scripts/MapEditor/UI/SwingsPerSecond.cs.meta, Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs
Essentially a copy-paste of the python code, only the total overall SPS is shown in the UI but the values for red, blue and total x Overall, peak and median are calculated
Bonus difficulty creation bugfix too
=> Swings per second

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/Audio/WaveformGenerator.cs, Assets/__Scripts/MapEditor/Detection/DingOnNotePassingGrid.cs, Assets/__Scripts/MapEditor/VisualFeedback.cs
Fixes for:
Notes not ticking when playing the same note twice, see:
https://discordapp.com/channels/702230714585710602/702232127755780197/763963021042253844
Spectrogram moving when pausing / changing UI mode etc. See:
https://discordapp.com/channels/702230714585710602/702232127755780197/767122138742128692
=> Small bugfixes

Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/MapEditor/CameraController.cs, Assets/__Scripts/MapEditor/CameraPosition.cs, Assets/__Scripts/MapEditor/CameraPosition.cs.meta, Assets/__Scripts/Settings/JSONSetting.cs, Assets/__Scripts/Settings/JSONSetting.cs.meta, Assets/__Scripts/Settings/Settings.cs
Probably more code in here for saving object types in the existing settings file than actually adding the feature.
Hotkeys pretty much copied from Starcraft 2.
F5-F8 are the default recall hotkeys.
Ctrl + <Key> = Set current location
And a second layer is accessible by adding shift allowing for 8 locations.
=> Camera location hotkeys

Assets/__Scripts/Platforms/Track Rings/TrackLaneRingsRotationEffect.cs
Pretty self explanatory, helpful link to current chroma code being emulated here:
https://github.com/Aeroluna/Chroma/blob/master/Chroma/HarmonyPatches/TrackLaneRingsRotationEffectSpawner.cs#L112
=> Add _speed property, apply new properties before multipliers

Assets/__Scenes/02_SongEditMenu.unity
Changed anchor types, seems to work 🤷
=> Fix text alignment in song edit menu

Assets/_Prefabs/MapEditor/Platforms/Dragons.prefab
Disclaimer: didn't even run this in the editor
=> Deleted lasers from dragons environment

Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
Simple options binds on the numpad if you don't want to press two keys
=> Add additional diagonal note keybinds on numpad

Assets/_Prefabs/MapEditor/Platforms/BTS.prefab, Assets/_Prefabs/MapEditor/Platforms/Big Mirror.prefab, Assets/_Prefabs/MapEditor/Platforms/Default.prefab, Assets/_Prefabs/MapEditor/Platforms/Dragons.prefab, Assets/_Prefabs/MapEditor/Platforms/FitBeat.prefab, Assets/_Prefabs/MapEditor/Platforms/Greenday.prefab, Assets/_Prefabs/MapEditor/Platforms/KDA.prefab, Assets/_Prefabs/MapEditor/Platforms/LinkinPark.prefab, Assets/_Prefabs/MapEditor/Platforms/Monstercat.prefab, Assets/_Prefabs/MapEditor/Platforms/Nice.prefab, Assets/_Prefabs/MapEditor/Platforms/Origins.prefab, Assets/_Prefabs/MapEditor/Platforms/Panic.prefab, Assets/_Prefabs/MapEditor/Platforms/Rocket.prefab, Assets/_Prefabs/MapEditor/Platforms/Triangle.prefab, Assets/__Scripts/Map/Obstacles/ObstacleAppearanceSO.cs, Assets/__Scripts/MapEditor/Loading/LoadInitialMap.cs, Assets/__Scripts/MapEditor/UI/Chroma/CustomColorsUIController.cs, Assets/__Scripts/Platforms/PlatformColors.cs, Assets/__Scripts/Platforms/PlatformDescriptor.cs
Bringing back the PR I closed a while back, but better
Store platform default colours and user options in separate values so we can reset properly when clicking the buttons
Also forced the alpha values to 1 for all these as SongCore refuses to load the values if they don't contain exactly 3 elements 🤔
=> SongCore overrides fixes

Assets/__Scripts/MapEditor/UI/PastNotesWorker.cs
Major fps drop when scrolling through a map with no notes :(
=> Fix creating past notes forever if no new ones pass the cursor

Assets/__Scenes/01_SongSelectMenu.unity
Not gonna lie, I don't know what m_Mode is
=> Fix song list refresh

Assets/__Scripts/Map/Notes/BeatmapNoteContainer.cs, Assets/__Scripts/MapEditor/Grid/Collections/NotesContainer.cs, Assets/__Scripts/MapEditor/Input/BeatmapInputController.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs
Also undid accidental change to raycaster
=> Make transparency cull dependent on user precision and editor scale

Assets/_Prefabs/MapEditor/Resources/BPM Change.prefab, Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs
Fix not being able to click on the block through the text. Tell me if there was a reason this raycaster was here?
Fixed metronome not changing when bpm block was passed
=> Bpm block fixes

Assets/Locales/FirstBoot Shared Data.asset, Assets/Locales/FirstBoot_en.asset, Assets/__Scenes/00_FirstBoot.unity, Assets/__Scenes/04_Options.unity, Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs, Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/FirstBootMenu.cs, Assets/__Scripts/UI/InputBoxFileValidator.cs, Assets/__Scripts/UI/Options/BetterToggle.cs, Assets/__Scripts/UI/Options/Settings Binders/LanguageDropdownSettingsBinder.cs
There's some code that somewhat-naively checks system specs and dynamically changes the default settings.
=> Spruce up the first boot menu, add language selection

Assets/__Scripts/MapEditor/Detection/DingOnNotePassingGrid.cs
Fix bongo boi
Don't factor in time correction when scheduling sounds, I think this is what was causing the sounds to be slightly early as they were being scheduled as if deltaTime had passed?
Waveform is certainly more consistent
=> Hitsounds round 2

Assets/_Graphics/Fonts/3DTeko.mat, Assets/_Graphics/Fonts/3DTeko.mat.meta, Assets/_Graphics/Shaders/3DText.shader, Assets/_Graphics/Shaders/3DText.shader.meta, Assets/_Prefabs/MapEditor/Resources/Event.prefab, Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Replace TMP in events with TM for performance. Event containers get created a lot faster as `CreateNewObject()` immediately sets the object as not active which causes the TMP to remove itself from a list in TMP_UpdateManager. As it's only just been created it will always be at the end of the list and do a full list traversal which adds up when there are a large number of objects visible.
Top is new. Only visible if you're looking for it.
=> Performance optimisations

Assets/_Prefabs/MapEditor/Platforms/Timbaland.prefab, Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeStepGradientPass.cs
Hide big bad gradient error
See: https://discord.com/channels/702230714585710602/702232127755780197/789142631631814676
Fix colour overrides on maps with no custom data
See: https://discord.com/channels/702230714585710602/702232127755780197/789486257151016960
Timbaland props are still wrong?
See: https://discord.com/channels/702230714585710602/702232127755780197/789527965003808769
=> Small fixes

Assets/_Prefabs/MapEditor/Platforms/KDA.prefab, Assets/__Scenes/03_Mapper.unity, Assets/__Scenes/999_PrefabBuilding.unity, Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/Map/Events/BeatmapEventContainer.cs, Assets/__Scripts/Map/Events/MapEvent.cs, Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs, Assets/__Scripts/MapEditor/Grid/CreateEventTypeLabels.cs, Assets/__Scripts/MapEditor/Grid/PauseToggleLights.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/Selection/BoxSelectionPlacementController.cs, Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeChromaPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLaserSpeedInterpolationPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLightingPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeStepGradientPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGeneratorPass.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs, Assets/__Scripts/MapEditor/UI/Strobe Generator/StrobeTextField.cs, Assets/__Scripts/MapEditor/UI/Strobe Generator/StrobeTextField.cs.meta, Assets/__Scripts/Platforms/LightsManager.cs, Assets/__Scripts/Platforms/PlatformDescriptor.cs
Not prop id but light id! Don't get excited, it only works for the spikes.
Bonus fix for being able to press keys in the strobe generator
=> Kda ground spikes

Assets/Locales/Mapper Shared Data.asset, Assets/Locales/Mapper_en.asset, Assets/_Prefabs/MapEditor/Platforms/KDA.prefab, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkContainer.cs, Assets/__Scripts/MapEditor/UI/Chroma/ColourPicker.cs, Assets/__Scripts/MapEditor/UI/KeybindUpdateUIController.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs, Assets/__Scripts/Settings/Settings.cs
I can break this out if needed.
Added KDA tentacles to objects that get hidden with 'L'
Allow bookmark renaming with right click
Add mirroring hotkeys:
- M = Same as UI button
- Shift+M = Colours only
- Alt+M = Mirror in time
Mirroring works on Chroma 2 gradients, swaps startColor and endColor
Changed it so that Chroma placment option is persistent and works even with the chroma menu closed
=> Various features

Assets/__Scripts/Platforms/Track Rings/TrackLaneRingsRotationEffect.cs
Fancy, don't need no more stacked events
=> Add new rotation field

Assets/__Scripts/MapEditor/AutoSaveController.cs, Assets/__Scripts/Singletons/SceneTransitionManager.cs, Assets/__Scripts/UI/PersistentUI.cs
Options available for other notifications, I've extended the wait time for save as the fade would previously have been 2 seconds.
=> Save notification doesn't fade, disappears early when save is complete

Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs, Assets/__Scripts/Platforms/LightsManager.cs
Rocket league has one in-game light id that maps to a number of lights in CM. A special environment indeed.
Could try and make a new mesh for the light but this was easier.
=> Rocket league lightid

Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedAction.cs, Assets/__Scripts/MapEditor/AudioTimeSyncController.cs, Assets/__Scripts/MapEditor/Grid/CreateEventTypeLabels.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Removed some dead code
Don't know why the play at end code stopped working but time was being returned as 0 🤷‍♂️
Fixed some issues related to shifting light id events around
=> More fixes

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
Bringing in behavior from MMA allowing for releasing the play button to rewind back to where playing began IF play was held for a given length of time.
I've been using it for a couple days no problem. Not sure if there's any dependencies I might have missed though, or if I am not following any coding standard properly, etc. Lemme know!
=> Holding Play and releasing after X time rewinds time

Assets/__Scripts/MapEditor/UI/Chroma/PaintSelectedObjects.cs
=> Fix painting objects with no customdata

Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
Multiple enumeration is pretty bad mmk
=> Enumerable needs to resolve now

Assets/_Prefabs/UI/Extension Button.prefab, Assets/_Prefabs/UI/Extension Button.prefab.meta, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/Extensions.meta, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButton.cs, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButton.cs.meta, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtonUI.cs, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtonUI.cs.meta, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtonUIBuilder.cs, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtonUIBuilder.cs.meta, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtons.cs, Assets/__Scripts/MapEditor/UI/Extensions/ExtensionButtons.cs.meta, PLUGINS.md
This PR adds an easy way for plugins to add buttons to the right side pop out panel of buttons in the editor. Usage is described in PLUGINS.md.
=> Extension buttons

Assets/__Scripts/Settings/Settings.cs
Probably don't merge this yet?
I'll promote whatever build is created after this is merged to be the current "stable" build in the launcher, so lets make it a good one. Very much focused on bug fixing atm so it may not have to be that long.
=> Change default release channel to stable

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
To fix the test failures in last PR :(
=> Handle null in UpdateQueuedValue

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/MapEditor/UI/KeybindUpdateUIController.cs, Assets/__Scripts/MapEditor/UI/Placement Controller UI/ColorTypeController.cs
Don't think anyone would mind moving the rotate in place keybinds to Alt + Q/E.
=> Added Colour Toggle Keybind

Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/Map/BeatSaberMap.cs, Assets/__Scripts/Requirements.meta, Assets/__Scripts/Requirements/ChromaReq.cs, Assets/__Scripts/Requirements/ChromaReq.cs.meta, Assets/__Scripts/Requirements/CinemaReq.cs, Assets/__Scripts/Requirements/CinemaReq.cs.meta, Assets/__Scripts/Requirements/LegacyChromaReq.cs, Assets/__Scripts/Requirements/LegacyChromaReq.cs.meta, Assets/__Scripts/Requirements/MappingExtensionsReq.cs, Assets/__Scripts/Requirements/MappingExtensionsReq.cs.meta, Assets/__Scripts/Requirements/NoodleExtensionsReq.cs, Assets/__Scripts/Requirements/NoodleExtensionsReq.cs.meta, Assets/__Scripts/Requirements/RequirementCheck.cs, Assets/__Scripts/Requirements/RequirementCheck.cs.meta, Assets/__Scripts/Requirements/SoundExtensionsReq.cs, Assets/__Scripts/Requirements/SoundExtensionsReq.cs.meta, Assets/__Scripts/UI/PersistentUI.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySettings.cs, Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs, Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs.meta, Assets/__Scripts/UI/SongEditMenu/EnvRemoval.cs, Assets/__Scripts/UI/SongEditMenu/EnvRemovalListItem.cs
This is on the same branch as the env enhancement changes as there are changes to the Chroma suggestion detection in there.
The intention here is to have a system that is easy for external plugins to register extra checks into so that's why I didn't just add checks in DifficultyBeatmap.
Checks for SoundExtensions and Cinema have been added here.
=> Refactor requirement and suggestion checking

Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/FirstBootMenu.cs, Assets/__Scripts/UI/Options/Settings Binders/ValidateDirectorySettingsBinder.cs
=> Use C# apis to normalise user-suplied paths rather than find/replace

Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/Map/BeatSaberMap.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySettings.cs, Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs, Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs.meta, Assets/__Scripts/UI/SongEditMenu/EnvRemoval.cs, Assets/__Scripts/UI/SongEditMenu/EnvRemovalListItem.cs
No new UI so you can only edit the id field of enhancements or add new values that do Contains removals.
If you open an old map it immediately considers it as changed and prompts you to save which will upgrade old removals to the new system.
=> Upgrade env removal to env enhancement

Assets/_Prefabs/Global/PersistentCanvas.prefab, Assets/_Prefabs/UI/InputField Container.prefab, Assets/_Prefabs/UI/Settings/Better Dropdown.prefab, Assets/_Prefabs/UI/Settings/Better InputField.prefab, Assets/_Prefabs/UI/Settings/JustButton.prefab, Assets/_Prefabs/UI/Settings/JustButton.prefab.meta, Assets/_Prefabs/UI/Settings/JustDropdown.prefab, Assets/_Prefabs/UI/Settings/JustDropdown.prefab.meta, Assets/_Prefabs/UI/Settings/JustTextInput.prefab, Assets/_Prefabs/UI/Settings/JustTextInput.prefab.meta, Assets/__Scenes/00_FirstBoot.unity, Assets/__Scripts/PluginLoader/UI.meta, Assets/__Scripts/PluginLoader/UI/Sprites.cs, Assets/__Scripts/PluginLoader/UI/Sprites.cs.meta, Assets/__Scripts/PluginLoader/UI/UIButton.cs, Assets/__Scripts/PluginLoader/UI/UIButton.cs.meta, Assets/__Scripts/PluginLoader/UI/UIDropdown.cs, Assets/__Scripts/PluginLoader/UI/UIDropdown.cs.meta, Assets/__Scripts/PluginLoader/UI/UITextInput.cs, Assets/__Scripts/PluginLoader/UI/UITextInput.cs.meta, Assets/__Scripts/UI/PersistentUI.cs
Maybe not the ideal solution for plugin UI but for fairly little effort this reduces the code I need in a plugin to create a dropdown by 20x
Basically just provides statically available prefabs that plugins can instantiate to create basic UI elements.
=> Plugin UI prefabs

Assets/__Scripts/MapEditor/Audio/AudioManager.cs
The idea is that pink noise should look flat, rather than white noise, because it much more closely resembles human hearing, and most music approximates the spectrum of pink noise.
Doesn't apply to 3D waveform because that already has a compensation of its own.
=> compensate for frequency bin in spectrogram

Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/SongSelectMenu/SongList.cs
Does what it says. Adds a new (hidden) setting that stores the last used sorting type.
=> remember song list sorting type

Assets/__Scripts/Platforms/PlatformDescriptor.cs
Fix panel and trianle rings not working in the "_nameFilter" field in Chroma ring events (Panel rings for FitBeat and Dragons and triangle rings for Triangle env)
Sorry for the pull request mess
=> Panel and Triangle Rings _nameFilter fix

Assets/Locales/SongEditMenu_en.asset, Assets/__Scripts/UI/SongInfoEditUI.cs
=> Song Time Offset warning works for negatives

Assets/__Scripts/MapEditor/Hit Sounds/HitSoundVolumeController.cs
I have come to repent for my sins
=> fix unwanted hitsound muting

Assets/_Prefabs/MapEditor/Platforms/Big Mirror.prefab, Assets/_Prefabs/MapEditor/Platforms/Default.prefab, Assets/_Prefabs/MapEditor/Platforms/Dragons.prefab, Assets/_Prefabs/MapEditor/Platforms/Nice.prefab, Assets/_Prefabs/MapEditor/Platforms/Triangle.prefab
Shrink BigMirror, Dragons, Nice, TheFirst, and Triangle environment ring lights to better reflect their actual size.
=> Shrink Ring Lights

Assets/__Scripts/MapEditor/Audio/WaveformGenerator.cs, Assets/__Scripts/MapEditor/AudioTimeSyncController.cs, Assets/__Scripts/MapEditor/Grid/MeasureLinesController.cs, Assets/__Scripts/MapEditor/Loading/LoadInitialMap.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/UI/SongInfoEditUI.cs
It was horribly broken and now that songTimeOffset is handled by adjusting the audio data it's interfering and no longer needed.
Also includes a bonus fix for the song offset warning
=> remove old song offset code

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkContainer.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkManager.cs, Assets/__Scripts/MapEditor/UI/SongTimelineHandleController.cs, Assets/__Scripts/MapEditor/UI/TimelineInputPlaybackController.cs, Assets/__Scripts/MapEditor/UI/TimelineInputPlaybackController.cs.meta
Enables:
- clicking and dragging on timeline
- clicking on bookmarks
- bookmark navigation keys
during playback.
This is done by pausing and resuming playback on pointer down/up. I have not found any obvious cases of undesired behavior with this approach, but if you have concerns feel free to bring them up.
=> enable various forms of timeline input during playback

Assets/Locales/Mapper Shared Data.asset, Assets/Locales/Mapper_en.asset, Assets/_Prefabs/Global/PersistentCanvas.prefab, Assets/_Prefabs/UI/Picker 2.0.prefab, Assets/_Prefabs/UI/Picker 2.0.prefab.meta, Assets/__Scenes/00_FirstBoot.unity, Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/HSVPicker/UI/ColorPicker.cs, Assets/__Scripts/Input/Master.cs, Assets/__Scripts/Input/Master.inputactions, Assets/__Scripts/Map/Bookmarks/BeatmapBookmark.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkContainer.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkManager.cs, Assets/__Scripts/UI/CM_ColorInputBox.cs, Assets/__Scripts/UI/CM_ColorInputBox.cs.meta, Assets/__Scripts/UI/PersistentUI.cs
Adds the ability for bookmarks to have a color stored with them, and adds a color selections dialog box to change the colors of said bookmarks
=> Bookmark colors

Assets/__Scripts/Map/Bookmarks/BeatmapBookmark.cs
Also might fix that random color not being random issue because unity's random color isn't used anymore
=> Fix bookmark color error on beatmap save

Assets/__Scenes/04_Options.unity, Assets/__Scripts/UI/Options/Search/SearchableSection.cs
=> Fix options search

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeChromaPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLightingPass.cs, Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeStepGradientPass.cs
Functions in game as of Chroma v2.5.7
=> Allow flash/fade/2.0 gradients on light id again

Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeChromaPass.cs
=> Prevent 2.0 gradients on lightID again

Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs
This had been bugging me for a while and it turned out to be a one line fix.
=> fix difficulty label not showing immediately on copy

Assets/__Scripts/Localization/Localization.asset
=> Add more loading messages

Assets/__Scripts/Singletons/Adb.cs, Assets/__Scripts/Singletons/AdbUI.cs
=> Fix stuff that I somehow didn't notice

Assets/__Scripts/UI/SongInfoEditUI.cs
=> Fix create zip button adding Info.dat twice

Assets/Input/Master.cs, Assets/Input/Master.inputactions, Assets/_Graphics/Textures And Sprites/Mapper/UIMode/UIMode Title.mat, Assets/__Scripts/Map/BeatmapObject.cs, Assets/__Scripts/Map/Obstacles/BeatmapObstacle.cs, Assets/__Scripts/Map/Obstacles/BeatmapObstacleV3.cs, Assets/__Scripts/MapEditor/Input/BeatmapObstacleInputController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs
Change custom data key in each object from `cd` to `customData`. Chroma notes should work in v3 map.
Since chroma currently doesn't support colorizing arc and chain, those logic remain unimplemented.
=> change v3 custom data key from cd to customData.

Assets/__Scenes/00_FirstBoot.unity, Assets/__Scenes/01_SongSelectMenu.unity, Assets/__Scenes/02_SongEditMenu.unity, Assets/__Scenes/04_Options.unity
Blame merge conflicts or something for the funny:
This yeets the extra script.
=> Remove duplicate additional camera

Assets/__Scripts/Platforms/LightingEvent.cs, Assets/__Scripts/Platforms/PlatformDescriptor.cs
Fades out faster.
Old vs New:
https://user-images.githubusercontent.com/68104413/166694849-b5f86578-a071-4aa8-8e3d-23ea579aeb5b.mp4
=> Apply easings to fade and flash events

Assets/Input/Master.cs, Assets/Input/Master.inputactions, Assets/__Scripts/Map/Arcs/BeatmapArcContainer.cs, Assets/__Scripts/Map/Chains/BeatmapChain.cs, Assets/__Scripts/Map/Chains/BeatmapChainContainer.cs, Assets/__Scripts/MapEditor/Input/BeatmapNoteInputController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ArcPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs
* Support dot arcs
* Chains should be fairly accurate
* Improvements to angleOffset usability
* Default hotkey is `Shift + Alt + Scroll`
=> Arc, chain, and angleOffset improvements

Assets/Locales/Options Shared Data.asset, Assets/Locales/Options_en.asset, Assets/_Graphics/Materials/Grids/Interface X Reveal.mat, Assets/_Graphics/Materials/Grids/Interface X.mat, Assets/_Graphics/Materials/PlacementGridBase.mat, Assets/__Scenes/03_Mapper.unity, Assets/__Scenes/04_Options.unity, Assets/__Scripts/Map/BeatSaberMap.cs, Assets/__Scripts/Map/Notes/BeatmapNoteContainer.cs, Assets/__Scripts/MapEditor/Grid/BookmarkRenderingController.cs, Assets/__Scripts/MapEditor/Grid/BookmarkRenderingController.cs.meta, Assets/__Scripts/MapEditor/Grid/GridRenderingController.cs, Assets/__Scripts/MapEditor/Grid/MeasureLinesController.cs, Assets/__Scripts/MapEditor/Mapping/PlatformToggleDisableableObjects.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkContainer.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkManager.cs, Assets/__Scripts/MapEditor/UI/CurrentDifficultyDisplay.cs, Assets/__Scripts/MapEditor/UI/CurrentDifficultyDisplay.cs.meta, Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/Options/Settings Binders/SettingsBinder.cs, Assets/__Scripts/UI/PersistentUI.cs
Ported @ShadowVirtues plugins ~~(butchering the code on the way)~~ as settings and adding some minor variable customisation to them.
* **GridBookmarks** - Additional cosmetic option
* **LongerGrid** - Adjustable length
* **ThinBookmarks** - Adjuststable width
* **SongNameDuringEditing** - Can toggle song/diff info
* **LessTransparentNotes** - Adjustable alpha
* **DisableTransitions**
* **DisablePlatformOnstart**
Logic is there. Just grouping and moving UI around.
=> Port CM plugins

Assets/Locales/SongEditMenu Shared Data.asset, Assets/Locales/SongEditMenu_en.asset, Assets/__Scenes/02_SongEditMenu.unity, Assets/__Scripts/UI/SongEditMenu/DifficultyInfo.cs, Assets/__Scripts/UI/SongEditMenu/EnvRemoval.cs
Featuring empty space. (*Please suggest for what can be added to that.*)
[Preview](https://cdn.discordapp.com/attachments/892494185909870602/963746220336103444/RT_field.mp4)
=> Add reaction time display in song info

Assets/Locales/Options Shared Data.asset, Assets/Locales/Options_en.asset, Assets/_Prefabs/UI/Settings/Options Section.prefab, Assets/__Scenes/04_Options.unity, Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/Singletons/Adb.cs, Assets/__Scripts/Singletons/AdbUI.cs
=> Allow disabling ADB if found in path (also fix downloading)

Assets/__Scripts/UI/SongEditMenu/DifficultySettings.cs
Reported in Chromapper server at https://discord.com/channels/702230714585710602/702232127755780197/1024384510189654016
=> Fix nullref when undoing custom diff name

Assets/Locales/SongEditMenu_en.asset, Assets/__Scenes/02_SongEditMenu.unity, Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs, Assets/__Scripts/UI/SongInfoEditUI.cs
- disable "open editor" button when no diff is selected
- prompt a save when leaving song info with unsaved changes
- new dialogue for opening nonexistent diff
Translations will need to be updated for dialogue box changes.
=> Improve handling for unsaved diff/info changes

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/Grid/Collections/BPMChangesContainer.cs, Assets/__Scripts/MapEditor/Input/BeatmapObstacleInputController.cs, Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
- makes copy/pasting around bpm changes reliable
- scales wall duration with bpm changes on copy/paste
- accounts for bpm changes when shifting selected objects (shift+arrows)
- updates wall duration tweak to use same bpm change handling logic
=> BPM change handling improvements

Assets/__Scripts/Extensions/BeatSaberSongExtensions.cs
=> fix remaining Info.dat casing once more

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
=> actually scale obstacle duration with bpm changes on copy/paste

Assets/__Scripts/Beatmap/Containers/ArcContainer.cs, Assets/__Scripts/Beatmap/Containers/ChainContainer.cs
- matches arc control point scaling to the game, should make them much more accurate
- fixes a tiny incorrect offset on the start of chains
=> minor fixes for arcs & chains

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/MapEditor/UI/Chroma/PaintSelectedObjects.cs
hopefully with no side effects 🦦
=> Fix chroma event and custom data being retained after placement

Assets/Tests/BeatmapV2Test.cs, Assets/Tests/BeatmapV3Test.cs, Assets/Tests/SimpleMirrorTest.cs, Assets/Tests/WallTest.cs, Assets/__Scripts/Beatmap/Base/BaseBpmEvent.cs, Assets/__Scripts/Beatmap/Base/BaseGrid.cs, Assets/__Scripts/Beatmap/Base/BaseObstacle.cs, Assets/__Scripts/Beatmap/Base/BaseSlider.cs, Assets/__Scripts/Beatmap/Containers/ArcContainer.cs, Assets/__Scripts/Beatmap/Containers/ChainContainer.cs, Assets/__Scripts/Beatmap/Converters/V2ToV3.cs, Assets/__Scripts/Beatmap/Converters/V3ToV2.cs, Assets/__Scripts/Beatmap/Helper/BeatmapFactory.cs, Assets/__Scripts/Beatmap/V2/V2Difficulty.cs, Assets/__Scripts/Beatmap/V2/V2Obstacle.cs, Assets/__Scripts/Beatmap/V3/V3Difficulty.cs, Assets/__Scripts/Beatmap/V3/V3Obstacle.cs, Assets/__Scripts/MapEditor/Loading/MapLoader.cs
it's only a dream
also updated obstacle test just to ensure data and visual isn't manipulated in any way (thanks beat games for having type and posY/height completely separated from both version)
alternative to current solution, it could just not set the value when setting attributes that doesnt exist on each version and return inferred attribute value (could be better option, need opinion)
**UPDATE 2023/01/31:** need to touch the conversion first before merge this PR
**UPDATE 2023/01/31:** various of fixes
=> Update obstacle model

Assets/__Scripts/Beatmap/Base/BaseDifficulty.cs, Assets/__Scripts/Beatmap/Converters/V2ToV3.cs, Assets/__Scripts/Beatmap/V2/V2Difficulty.cs, Assets/__Scripts/Beatmap/V3/V3Difficulty.cs
sometimes i think
but then i forget
=> Fix point definitions custom data

Assets/__Scripts/Beatmap/V2/V2Difficulty.cs, Assets/__Scripts/Beatmap/V3/V3Difficulty.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ArcPlacement.cs
=> Fix certain objects get yeet on save in edit menu

Assets/Tests/EventTest.cs, Assets/Tests/SimpleMirrorTest.cs, Assets/Tests/Util/CheckUtils.cs, Assets/__Scripts/Beatmap/Base/BaseBpmEvent.cs, Assets/__Scripts/Beatmap/Base/BaseColorBoostEvent.cs, Assets/__Scripts/Beatmap/Base/BaseEvent.cs, Assets/__Scripts/Beatmap/Base/BaseRotationEvent.cs, Assets/__Scripts/MapEditor/Grid/Rotation/GridRotationController.cs, Assets/__Scripts/MapEditor/Grid/Rotation/Rotation90DegreesWarningController.cs, Assets/__Scripts/MapEditor/Grid/Rotation/RotationCallbackController.cs, Assets/__Scripts/MapEditor/Grid/Rotation/RotationDisplayController.cs, Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs
=> Rotation event fix

Assets/__Scripts/Singletons/Adb.cs
It's been made apparent that for whatever reason the executable permissions required to invoke `adb` on Mac or Linux are lost when extracting the zip. 
See #446's steps
The zip does have the permission attributes as shown here: (windows and mac respectively)
This also cleans up a memory leak when downloading and reading the zip.
I haven't tested this on my Linux machine, though I'd greatly appreciate if someone could vouch for it.
I'll leave it as a ready PR regardless though.
=> ADB permissions on Mac/Linux

Assets/__Scripts/Beatmap/Appearances/ObstacleAppearanceSO.cs, Assets/__Scripts/Beatmap/Base/BaseObstacle.cs, Assets/__Scripts/Beatmap/Base/Customs/INoodleExtensions.cs, Assets/__Scripts/Beatmap/Containers/ObstacleContainer.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs, Assets/__Scripts/MapEditor/UI/MirrorSelection.cs
Dev currently will default CustomSize `z` to 0 instead of it being optional so this fixes that.
=> Obstacle CustomSize optional z fix

Assets/__Scripts/Beatmap/Base/BaseDifficulty.cs
=> small BPM conversion fix

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
=> remove unnecessary song bpm time conversion on paste

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
=> Fix placement flicker

Assets/__Scripts/MapEditor/Grid/Collections/CustomEventGridContainer.cs
=> Handle null AssignPlayerToTrack

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/CameraManager.cs, Assets/__Scripts/MapEditor/CameraManager.cs.meta, Assets/__Scripts/MapEditor/Input/BeatmapInputController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/MapEditor/UI/UIMode.cs
* Fix raycast coming from inactive camera
* Delete tool is only active with Application focus
=> Camera fixes

Assets/__Scenes/03_Mapper.unity, Assets/__Scripts/MapEditor/TimeMappingController.cs, Assets/__Scripts/MapEditor/TimeMappingController.cs.meta, Assets/__Scripts/MapEditor/UI/Counters+/CountersPlusController.cs
This Pull Request implements a more robust form of updating the time spent in a map. This new version should be more accurate, and less prone to floating point error.
=> Better time keeping

Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
* Instead of deleting and spawning on FinishDrag, we delete on StartDrag and spawn on FinishDrag.
* Remove some copying while dragging
=> Fix dragging objects not working

Assets/Locales/Options Shared Data.asset, Assets/Locales/Options_da.asset, Assets/Locales/Options_de.asset, Assets/Locales/Options_en-OWO.asset, Assets/Locales/Options_en-PT.asset, Assets/Locales/Options_en.asset, Assets/Locales/Options_es-ES.asset, Assets/Locales/Options_et.asset, Assets/Locales/Options_fi.asset, Assets/Locales/Options_fr.asset, Assets/Locales/Options_ja.asset, Assets/Locales/Options_ko.asset, Assets/Locales/Options_nl.asset, Assets/Locales/Options_ru.asset, Assets/Locales/Options_sv-SE.asset, Assets/Locales/Options_zh-CN.asset, Assets/__Scenes/03_Mapper.unity, Assets/__Scenes/04_Options.unity, Assets/__Scripts/MapEditor/Grid/InterfaceRenderingController.cs, Assets/__Scripts/MapEditor/Grid/InterfaceRenderingController.cs.meta, Assets/__Scripts/Settings/Settings.cs, Assets/__Scripts/UI/Options/BetterSlider.cs
while chromapper is currently blowing up with save issues from my own rewrites... how about a simple appearance setting? :)
one of a few requests from mawntee
=> Add Interface Opacity

Assets/_Prefabs/Global/PersistentCanvas.prefab, Assets/__Scripts/UI/PersistentUI.cs
Fixes tooltip limits not matching the screen
=> Limit tooltips correctly

Assets/__Scripts/MapEditor/Detection/BeatmapObjectCallbackController.cs, Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs, Assets/__Scripts/MapEditor/Grid/Collections/ObstacleGridContainer.cs, Assets/__Scripts/MapEditor/Mapping/Selection/BoxSelectionPlacementController.cs
Makes the Shift+T track filter actually work! It hasn't done anything for as long as I've seen.
=> Fix track filter

Assets/Tests/Util/TestUtils.cs, Assets/_Prefabs/UI/Song Folder.prefab, Assets/_Prefabs/UI/Song Folder.prefab.meta, Assets/__Scenes/01_SongSelectMenu.unity, Assets/__Scripts/BeatSaberSong.cs, Assets/__Scripts/Extensions/BeatSaberSongExtensions.cs, Assets/__Scripts/MapEditor/MapExporter.cs, Assets/__Scripts/UI/InputBoxFileValidator.cs, Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs, Assets/__Scripts/UI/SongInfoEditUI.cs, Assets/__Scripts/UI/SongSelectMenu/CreateNewSong.cs, Assets/__Scripts/UI/SongSelectMenu/SongList.cs, Assets/__Scripts/UI/SongSelectMenu/SongListItem.cs
* If a SongCore `folder.xml` exists, they will now be displayed in song select
* More folders
* No support for adding folders yet
=> Display SongCore folders in SongSelect

Assets/__Scripts/MapEditor/Audio/AudioManager.cs
=> Fix linux vulkan (at least amdgpu)

Assets/__Scripts/Beatmap/V3/V3Difficulty.cs
Loading is correctly "fakeBurstSliders", but saving is not
Thank Mawntee for noticing
=> Incorrect key when saving fake burst sliders

Assets/_Graphics/Textures And Sprites/UI/Editor UI/Metronome/Metronome.controller, Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs
Fixed metronome double tick
Also changed some spots to use `metronomeActive` instead of `metronomeVolume`
=> Fix metronome double tick

Assets/__Scripts/Requirements/RequirementCheck.cs, Assets/__Scripts/Requirements/VivifyReq.cs, Assets/__Scripts/Requirements/VivifyReq.cs.meta
=> Vivify requirement checker

Assets/_Graphics/Shaders/Editor/Spectrogram.shader, Assets/__Scripts/UI/SongEditMenu/AudioPreviewGenerator.cs
=> make spectrogram cursor scale independent of song bpm

Assets/__Scripts/Beatmap/Info/V4/V4Info.cs, Assets/__Scripts/UI/SongSelectMenu/SongListItem.cs
saves duration from loaded song, and uses stored value for duration display in song list if available
=> support v4 info songDuration

Assets/__Scripts/MapEditor/CameraController.cs
Unsure if this is just a macOS issue and no idea if this fix works for everyone, but hey it's something.
The fix I implemented is to just ignore the first few frames of mouse input after right clicking, then gradually ease into normal camera control
Before:
https://github.com/user-attachments/assets/f4d32543-6f9d-479a-be02-4ba6e2c3a165
After:
https://github.com/user-attachments/assets/be5b9a37-7c8d-4eab-a3bb-ea279f44985f
=> Fix camera controller snapping on first mouse move

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
=> fix spectro alignment on track length not multiple of 4

Assets/Tests/NoteTest.cs, Assets/__Scripts/Beatmap/Base/BaseBpmEvent.cs, Assets/__Scripts/Beatmap/Base/BaseNJSEvent.cs, Assets/__Scripts/BeatmapActions/Beatmap Action Containers/BeatmapActionContainer.cs, Assets/__Scripts/BeatmapActions/Beatmap Actions/ActionCollectionAction.cs, Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedAction.cs, Assets/__Scripts/BeatmapActions/IMergeableAction.cs, Assets/__Scripts/BeatmapActions/IMergeableAction.cs.meta, Assets/__Scripts/MapEditor/Input/BeatmapArcInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapBPMChangeInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapChainInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapNJSEventInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapNoteInputController.cs, Assets/__Scripts/MapEditor/Input/BeatmapObstacleInputController.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/CommonNotePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
quality of life improvement with undo/redo of repeated actions, such as tweaking values with alt+scroll
currently not tested with united mapping, PR is marked as draft until this is done
=> merge specific actions when repeated

Assets/__Scripts/Beatmap/Animations/ObjectAnimator.cs, Assets/__Scripts/Beatmap/Base/BaseArc.cs, Assets/__Scripts/Beatmap/Base/BaseBpmEvent.cs, Assets/__Scripts/Beatmap/Base/BaseChain.cs, Assets/__Scripts/Beatmap/Base/BaseDifficulty.cs, Assets/__Scripts/Beatmap/Base/BaseEvent.cs, Assets/__Scripts/Beatmap/Base/BaseGrid.cs, Assets/__Scripts/Beatmap/Base/BaseNJSEvent.cs, Assets/__Scripts/Beatmap/Base/BaseNote.cs, Assets/__Scripts/Beatmap/Base/BaseObject.cs, Assets/__Scripts/Beatmap/Base/BaseObstacle.cs, Assets/__Scripts/Beatmap/Base/BaseSlider.cs, Assets/__Scripts/Beatmap/Base/BaseWaypoint.cs, Assets/__Scripts/Beatmap/Base/Customs/BaseBookmark.cs, Assets/__Scripts/Beatmap/Base/Customs/BaseBpmChange.cs, Assets/__Scripts/Beatmap/Info/V4/V4Info.cs, Assets/__Scripts/MapEditor/Loading/MapLoader.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ArcIndicatorPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BPMChangePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BombPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ChainIndicatorPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NJSEventPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs, Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkManager.cs
and a bit of refactoring while I was at it
=> fix song bpm duration recompute when obstacle time changes

Assets/_Graphics/Textures And Sprites/Mapper/ColorTypePicker.meta, Assets/_Graphics/Textures And Sprites/Mapper/UIMode/UIMode Title.mat, BUILD.md, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectVersion.txt
Tested and confirmed to fix #549
=> Update to Unity 2021.3.45f

Assets/__Scripts/Beatmap/Containers/ChainContainer.cs, Assets/__Scripts/Beatmap/Containers/NoteContainer.cs, Assets/__Scripts/MapEditor/Grid/Collections/ChainGridContainer.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ChainIndicatorPlacement.cs, Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
Chain head note should be much more consistent than having erratic transform placement, performance wise dont see a difference so should be good?
Haven't fully tested it with various scenario, basic interaction seems to be ok
This is for hot fix patch before push for major dev update, these may get rewritten for better implementation
=> Fix weird chain head behaviour
