Caeden117/ChroMapper

Assets/__Scripts/MapEditor/CameraController.cs

Allows camera to look straight down/up without bugging out
modified:   Assets/__Scripts/MapEditor/CameraController.cs

Fix pepega camera

---

Assets/Plugins/x86.meta
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs

In accordance with:
https://docs.google.com/spreadsheets/d/1vCTlDvx0ZW8NkkZBYW6ecvXaVRxDUKX7QIoah9PCp_c/htmlview
also pls ignore x86.meta idk what its doin
modified:   Assets/__Scripts/Map/Events/BeatmapEventContainer.cs

Fix middle-click events flipping to incorrect value

---

Assets/Plugins/x86.meta
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
Assets/__Scripts/MapEditor/AutoSaveController.cs
Assets/__Scripts/MapEditor/CameraController.cs
Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs
Assets/__Scripts/MapEditor/UI/CountersPlusController.cs

- Ctrl+Scroll revamped to change precision based on current precision. i.e. scrolling up on 1/3 will adjust the precision to 1/6.
- Added a counter that tracks amount of objects selected. This is independent of the Counters+ option in settings and it updates every frame.
- Ctrl+S no longer saves while moving the camera, allowing players to move the camera down and backwards without saving.
- Camera movement revamped: sensitivity drastically nerfed (seriously why was the camera on crack), movement speed nerfed but sprint reintroduced, and camera will no longer slides but instead ceases all movement when player stops input.
- Grid under notes and cursors has been flattened to prevent clipping with notes and events, also I'm not really sure why its in two layers.
- Autosaves reworked to …

Various changes

---

Assets/__Scenes/00_FirstBoot.unity
Assets/__Scripts/MapEditor/Detection/BongoCat.cs

- Removed the redundant tooltip on the button in 00_FirstBoot
- Bombs no longer lobotomize Bongo Cat
- Clamped Bongo's timeout to prevent Bongo's arm from sticking down for too little or too long

Bongo Cat changes

---

Assets/HSVPicker/UI/ColorPickerMessageSender.cs
Assets/HSVPicker/UI/ColorPresets.cs
Assets/__Scenes/00_FirstBoot.unity
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Map/BeatmapObjectContainer.cs
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/Map/Events/EventAppearanceSO.cs
Assets/__Scripts/MapEditor/Grid/MeasureLinesController.cs
Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/UI/BPM Tapper/BPMTapperController.cs
Assets/__Scripts/MapEditor/UI/CountersPlusController.cs
Assets/__Scripts/MapEditor/UI/MirrorSelection.cs
Assets/__Scripts/MapEditor/UI/MirrorSelection.cs.meta
Assets/__Scripts/MapEditor/UI/Placement Controller UI/EventPlacementUI.cs
Assets/__Scripts/MapEditor/UI/Placement Controller UI/NotePlacementUI.cs
Assets/__Scripts/MapEditor/UI/UIWorkflowToggle.cs
README.md

- Small change on README.md
- Made Counters+ a little smaller to be less obtrusive and moved it to be symmetrical to song time on the right
- Added Reset button to BPM Tapper
- Fixed wonky hit box for "Let's Go!" on 00_Firstboot
- Measure line number will now properly flip to other grid when clicking the workflow button
- Measure line number now remains flush with grid after moving (previously started floating whenever it shifted sides)
- Can now middle click presets in the Chroma panel to override the preset
- Added a dedicated delete tool on the top bar
- Added a mirror selection tool on the top bar
- Cleaned up some pepega code in KeybindsController.cs (unfinished)
- Shift+M3 will now only delete a single object when you have a selection instead of deleting the entire selection

big brain coder

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/Detection/BongoCat.cs
Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/UI/Info Panel/ChroMapperInfo.txt
Assets/__Scripts/MapEditor/UI/Placement Controller UI/EventPlacementUI.cs
Assets/__Scripts/MapEditor/UI/Placement Controller UI/NotePlacementUI.cs

- Bongo Cat will now properly smack down on notes when there are no notes afterwards
- Backspace added as a key for deleting a selection
- Few additions to controls listing
- Some jankiness removed from top bar in 03_Mapper
- Some jankiness added to top bar in 03_Mapper
- Key binds reworked to toggle the buttons on the top bar and in turn do their effects through that (Instead of key binds running their own duplicate code directly) This should also mean that the buttons in top bar are correctly highlighted when using key binds
Lots of code I commented out that I probably should have just deleted

pepega code coming through

---

Assets/HSVPicker/UI/ColorPicker.cs
Assets/__Scenes/03_Mapper.unity
Assets/__Scenes/04_Options.unity
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/Map/Events/EventAppearanceSO.cs
Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/UI/MirrorSelection.cs
Assets/__Scripts/MapEditor/UI/Placement Controller UI/EventPlacementUI.cs
Assets/__Scripts/MapEditor/UI/PostProcessingController.cs
Assets/__Scripts/Settings/Settings.cs
Assets/__Scripts/UI/Options/OptionsEditorSettings.cs

- Fix: Mirror selection tool now works on non-mapping extensions walls (can't believe I forgot to do that)
- Added "Invert Precision Scroll" option in 04_Options, this will invert the direction you scroll the mouse wheel to change precision step
- Fix: You can now correctly hover over any part of the scroll area in 04_Options to scroll with mouse wheel (this was fixed by placing a fully transparent image over the whole area)
- Fix: Bumped up scroll sensitivity in 04_Options so you can actually scroll with mouse wheel (note: this may cause problems on non-windows devices and may need to be adjusted)
- Changed event placement to no longer overwrite existing events at the same timestamp, will instead no longer place (parameter still in function to allow old functionality in case we want this …

Gotta earn that purple name

---

Assets/_Graphics/Textures And Sprites/UI/Options.meta
Assets/__Scripts/BeatSaberSong.cs
Assets/__Scripts/BeatmapActions/Beatmap Action Containers/BeatmapActionContainer.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectDeletionAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectPlacementAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/NodeEditorUpdatedNodeAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/StrobeGeneratorGenerationAction.cs
Assets/__Scripts/BeatmapActions/BeatmapAction.cs
Assets/__Scripts/Map/BeatmapObjectContainer.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs
Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/NotesContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/ObstaclesContainer.cs
Assets/__Scripts/MapEditor/Grid/Tracks/TracksManager.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BombPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/CustomEventPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

- ChroMapper now places an `_editor` field in `Info._customData` to identify itself.
- BeatMapper has been using this field in the past, so why not add on to it?
- Actions have been improved
- Comments to actions have been added to make potential debugging faster.
- Actions involving multiple objects now do not stack `BeatmapObjectDeletionAction`s when undoing (Such as undoing a Paste or a gradient made with Strobe Generator)
- I'm about to switch to Unity `2019.3.0f6` to convert CM to DOTS and ECS. I'll make a new branch for this.

Development (1-29-20)

---

Assets/__Scripts/MapEditor/UI/BPM Tapper/BPMTapperController.cs
Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
Assets/__Scripts/MapEditor/UI/UIMode.cs

Also made it so if Node Editor or BPM Tapper is open you can't switch UIMode.
[Node Editor can be triggered with UIMode](https://app.gitkraken.com/glo/board/5e1b3f6f0af39d00106c44f0/card/5e69952d039f800014b1e347)

Made UIMode not change when Node or BPM Tapper is open.

---

Assets/_Graphics/Shaders/Editor/Grid ZDir.shader
Assets/__Scripts/MapEditor/Grid/Collections/BPMChangesContainer.cs

Max shader size is 64KB for DirectX but only 16KB for Metal (and OpenGL but we don't talk about OpenGL). Compiled shader for Windows used to look like:
```
Constant Buffer "$Globals" (65536 bytes) on slot 0 {
Float _GridThickness at 0
Float _GridSpacing at 4
Float _Offset at 8
Vector4 _GridColour at 16
Vector4 _BaseColour at 32
Vector1 _BPMChange_Times[2046] at 64
Vector1 _BPMChange_BPMs[2046] at 32800
ScalarInt _BPMChange_Count at 65524
Float _EditorScale at 65528
}
```
Exactly 64KB!
Thankfully the types on Metal uses fewer bytes (16 bytes for a float is crazy though?):
```
Constant Buffer "$Globals" (16424 bytes) {
Float _GridThickness at 0
Float _GridSpacing at 4
Float _Offset at 8
Vector4 _GridColour at 16
Vector4 _BaseColour at 32
Vector1 _BPMChange_Times[2046] at 48
Vector1 …
```

Fix Grid ZDir shader on MacOS

---

Assets/__Scripts/UI/FirstBootMenu.cs

If you have games on an external hard drive or library location then steam can run then without ever "installing" them, thus uninstall registry entries aren't created. When booting steam on a fresh windows install it "fixes" the registry which at least puts in the install folder for the client itself and using this we can read steam files to find the game directory.
This is pretty much how MMA2 finds the steam directory.
I've left the existing code as it's a lot simpler if the registry key *does* exist but this code should work in any case where the existing code does.

Steam discovery doesn't work on fresh install

---

Assets/__Scripts/MapEditor/Mapping/Selection/BoxSelectionPlacementController.cs

Example selecting from the lighting side to the waveform side. The old code sets the boundary starting from the division between the right-side lanes instead when moving in this direction the origin is offset and the total size is increased to include the extra lanes.
I've also removed the `IsSelecting = false;` and moved the `OnPhysicsRaycast` out of the placement event as this triggers before the click event that causes notes to be placed. This prevents new notes being placed when ending selection.
Before:
After:

Fix object selection box

---

Assets/_Prefabs/UI/ContributorItemContainer.prefab
Assets/__Scenes/00_FirstBoot.unity
Assets/__Scenes/05_Contributors.unity
Assets/__Scripts/Input/Master.cs
Assets/__Scripts/Input/Master.inputactions
Assets/__Scripts/UI/CM_DialogBox.cs
Assets/__Scripts/UI/Contributors/ContributorListItem.cs
Assets/__Scripts/UI/Contributors/ContributorsController.cs
Assets/__Scripts/UI/Contributors/ContributorsEditController.cs
Assets/__Scripts/UI/SongSelectMenu/SongList.cs

So I've playing with code, 3d meshes. Today is UI time. I picked the least connected piece of the UI to test the water somewhat.
The contributor view was sort of limited to 8 contributors except for when it wasn't. The previous version of this code kept two lists. One list of data and another of visible objects. If you kept clicking new you could add more data than there was space to display. And if you clicked remove the list would stay full for a while respecting the number added. I also had fun with this:
1. Add a few items
2. Click edit on one in the middle
3. Clear the list
4. Click save multiple times
It remembers where in the list I was editing and adds that number of items???
The mis-alignment of the text boxes also really triggers me
(Aside) I'm not a fan of the default …

Update contributor view

---

Assets/_Prefabs/MapEditor/Platforms/Default.prefab
Assets/_Prefabs/MapEditor/Platforms/Monstercat.prefab
Assets/_Prefabs/MapEditor/Platforms/Nice.prefab
Assets/_Prefabs/MapEditor/Platforms/Triangle.prefab

Maybe you were expecting a PR for some UI work? Psych! [It's laser time](https://www.youtube.com/watch?v=NsuZphC9bsw).
The lasers in the background in Nice, Triangle, Crab Rave and Monstercat don't match how they look in game. At some point the background lasers were cut in half and the top sections either moved to the center lighting or were removed.
Also bonus fix for monstercat logo in red.
See before/after/in-game screenshots:

Fix background lasers following different pattern than in the game

---

Assets/__Scripts/MapEditor/Audio/SpectrogramChunk.cs

It seems the 3d spectogram sync issue I tried to fix is worse at higher bpms, my original test was at 60bpm. This now works at least between that and 256 bpm. Please don't ask why.

Fix spectogram sync

---

Assets/__Scripts/BeatSaberSong.cs
Assets/__Scripts/UI/SongEditMenu/CharacteristicSelect.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs

Already had code that ignores duplicated difficulties within a characteristic but didn't handle duplicated characteristics well.
Mostly because I don't really know how the file gets into this kind of state, but this code helps it be self-healing.

Group duplicated characteristic blocks in info.dat

---

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs

To reproduce these:
* Set precision to 1/2
* Move into a beat
* Create a bookmark
* Set precision back to 1/1
* Navigate to bookmark
With my mouse hovering over the grid here this is not where I expect the note to be placed.
Likewise this seems to be intended behaviour and it feels really weird to me that pointing specifically at the vertical grid moves my placement back to the beat but pointing anywhere else doesn't.
With this change, notes can be placed in increments of the current precision _from_ the current position and round how you would expect. So either:
Or
depending on which your mouse is closer to

Tweak placement snapping

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/Audio/WaveformGenerator.cs
Assets/__Scripts/UI/SongInfoEditUI.cs

Adds a second gradient for the 2d waveform and fixes opening explorer when paths have funky characters

Fix open explorer with commas in path. Increase waveform contrast

---

Assets/_Graphics/Materials/Notes/Bombs.mat
Assets/_Graphics/Materials/Notes/Unassigned.mat
Assets/_Prefabs/MapEditor/Objects/Unassigned Note.prefab

Fixes issues with the grid rendering over bombs at certain angles where it shouldn't

Set bomb material and switched shader to opaque

---

Assets/__Scripts/Map/BeatmapObjectContainer.cs
Assets/__Scripts/Map/Obstacles/BeatmapObstacle.cs

Fix selection outline not showing. I think someone had changed which of simple / shiny blocks were enabled in the prefab and we were only searching for selection materials in enabled children.
Allow deleting noodle walls. Re-added the json equality check for noodle as the DeleteObject method requires this to match to delete things.

Small fixes

---

Assets/Editor/CrowdIn.cs
Assets/Locales/Contributors.asset
Assets/Locales/FirstBoot.asset
Assets/Locales/SongEditMenu.asset
Assets/Locales/SongSelectMenu.asset

I found a forum post that explained this as a bug in the current version of unity's library, this makes it so that things don't get re-orphaned when restarting unity.
https://forum.unity.com/threads/english-column-disappearing-automatically.932532/#post-6100209

Make fix orphans permenant by marking broken collections as dirty

---

Assets/__Scenes/02_SongEditMenu.unity
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectPlacementAction.cs
Assets/__Scripts/MapEditor/AutoSaveController.cs
Assets/__Scripts/MapEditor/Grid/Collections/NotesContainer.cs
Assets/__Scripts/MapEditor/Input/BeatmapNoteInputController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
Assets/__Scripts/Settings/Settings.cs
Assets/__Scripts/UI/SongEditMenu/CharacteristicSelect.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs
Assets/__Scripts/UI/SongInfoEditUI.cs

- Fixes a missing translation key due to a rogue space in `auto .save`
- Fix two bugs with note snapping see:
- https://streamable.com/7ftvjq - Notes can flip completely over if one is a dot and one is an arrow and they are indexed in the wrong order
- Another where placing and then toggling the colour of a dot note would infinitely rotate another dot note. This is mostly fixed by applying the refresh to both original and new when toggling colours but as the `+=` were removed from the rest of this function I don't see why this should keep them, seems to work fine like this.
- Fix having to undo twice when dragging notes and bombs. I don't know if the fact you need to be in the matching placement mode is desirable for bombs/notes/walls etc. But currently both note and wall placement …

Various fixes

---

Assets/_Graphics/Textures And Sprites/Backgrounds/SaberBackground1.jpg.meta
Assets/_Graphics/Textures And Sprites/Backgrounds/SaberBackground2.jpg.meta
Assets/_Graphics/Textures And Sprites/Backgrounds/SaberBackground3.jpg.meta
Assets/_Graphics/Textures And Sprites/Backgrounds/SaberBackground4.jpg.meta
Assets/_Graphics/Textures And Sprites/Backgrounds/SaberLoading.jpg.meta
Assets/_Graphics/Textures And Sprites/UI/BeatsaberSpriteSheet.png.meta
Assets/_Graphics/Textures And Sprites/UI/Editor UI/metronome.png.meta
Assets/_Graphics/Textures And Sprites/UI/Options/Tab Icons/Arrow Keys.png.meta
Assets/_Graphics/Textures And Sprites/UI/Options/Tab Icons/Keyboard & Mouse.png.meta
Assets/_Graphics/Textures And Sprites/UI/Warning.png.meta

Most of the other images already had compression set. Set a few of the textures with no compression to Normal Quality.
Reduces the compressed output size by about 13MB

Add image compression to backgrounds to reduce filesize

---

Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs

This is a minor fix for the metronome.
In the current implementation the ticking will drift from the target bmp depending on the fps.
So about 118/120bpm or 150/155bpm at 60fps in my testing.
The change preserves the already elapsed time into the new frame.
I also tried to find a constant high precision timer for unity since the current one still only fires at each frame at max. But it seems unity cannot do that. Unless maybe with a own thread for that, however that seems overkill.

Fixes metronome drift

---

Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

Shift + up and down won't refresh window-aligned notes
Don't know if the same as:
https://discordapp.com/channels/702230714585710602/702232127755780197/768040651383635969
Alt+Shift+Left click shouldn't move blocks
https://discordapp.com/channels/702230714585710602/702232127755780197/767186327682678825
alt+left click and alt+right click will deselect a note that was previously selected
https://discordapp.com/channels/702230714585710602/702232127755780197/767890235005730847
Fixed some undo bugs by using IsConflictingWith, I don't know how objects are getting confused here but they certainly were. I couldn't work out how to reproduce it every time either...

More bugfixes

---

Assets/__Scripts/Platforms/Track Rings/TrackLaneRingsRotationEffect.cs

Updated to match chroma
See https://github.com/Aeroluna/Chroma/blob/master/Chroma/ChromaRingsRotationEffect.cs#L64
Fix for wonky rounding:
```        float a = 2.5f;
for (int i = 0; i < 10; i++)
{
Debug.Log(Mathf.RoundToInt(a));
a++;
}
```

Change ring update loop code to match chroma

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs
Assets/__Scripts/MapEditor/Grid/CreateEventTypeLabels.cs
Assets/__Scripts/MapEditor/Grid/LaneInfo.cs
Assets/__Scripts/MapEditor/Grid/LaneInfo.cs.meta
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

Refactor lanes, hold what's being displayed in list in memory and use that to map between co-ordinates and types instead of static array lookups that break when we start hiding lanes.
Hide 360/90 when not in a 360 map so that we don't get random warnings all the time
Fix shifting events off the edge of the world

Lane refactor

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/Map/IBeatmapObjectBounds.cs
Assets/__Scripts/Map/IBeatmapObjectBounds.cs.meta
Assets/__Scripts/Map/Notes/BeatmapNote.cs
Assets/__Scripts/Map/Obstacles/BeatmapObstacle.cs
Assets/__Scripts/Map/Obstacles/BeatmapObstacleContainer.cs
Assets/__Scripts/Map/Obstacles/ObstacleBounds.cs
Assets/__Scripts/Map/Obstacles/ObstacleBounds.cs.meta
Assets/__Scripts/MapEditor/Mapping/Selection/BoxSelectionPlacementController.cs
Assets/__Scripts/Platforms/PlatformColors.cs.meta

Refactor selection box to not use a BoxColider as now that objects are not loaded all the time this has funky results.
Instead I've implemented ways of working out where the centre of most objects are and a not terrible way of working out if they are within the bounding box.
The bounding box is also itself bounded to the track being selected, no more can you move your cursor across tracks only to find the filter doesn't allow that anyway.
The biggest impact here is that, instead of selecting things if any part of them is within the bounding area, things are only selected when over half of them is in. I think this only really affects precision placement. Thoughts welcome.

Make box select great again

---

Assets/__Scripts/MapEditor/Grid/Collections/NotesContainer.cs
Assets/__Scripts/MapEditor/Grid/CreateEventTypeLabels.cs

Show rotation lanes even outside of 360/90 maps if rotation events exist
Removed some more linq because it is "slow" and called 100s of times when scrolling through the map and cache the result of 1/pow(10, 3) ~0.15ms -> 0.05ms in deep profiling

Small fix/optimisation

---

Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedAction.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

So first we call UpdateGridPosition, then set PropagationEditing which updates the locations of all the objects and then we call RefreshPool(true) which recycles all the containers we just made sure were in the right places. Seems efficient.
This is worst when in prop view as the locations of all the events are updated _for each event being moved_
Moved to a plinq which may be slower for small number of events, but fast enough for action from user input.
Also cut down on calls to generate copy, as after this recent commit two calls here are superfluous https://github.com/Caeden117/ChroMapper/commit/0a177c1c3abb1045efdc783be3d648f1fa8774e1

Prop shift optimisations

---

Assets/HSVPicker/UI/HexColorField.cs
Assets/__Scripts/Input/ChroMapper/CMInputCallbackInstaller.cs
Assets/__Scripts/MapEditor/CameraController.cs
Assets/__Scripts/MapEditor/Input/BeatmapInputController.cs
Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Assets/__Scripts/MapEditor/UI/Bookmarks/BookmarkManager.cs
Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
Assets/__Scripts/MapEditor/UI/PauseManager.cs
Assets/__Scripts/UI/CM_DialogBox.cs
Assets/__Scripts/UI/CM_InputBox.cs
Assets/__Scripts/UI/Contributors/ContributorListItem.cs
Assets/__Scripts/UI/InputBoxFileValidator.cs
Assets/__Scripts/UI/Options/OptionsController.cs

Sort the bookmarks array, fixes weird next/previous behaviour see https://discordapp.com/channels/702230714585710602/702232127755780197/779680425391292426
Harden up CMInputCallbackInstaller to stop rogue classes locking out the user, each type can only have a single block of an input type. Fixes editing colour selection as that called disable for each keystroke see https://discordapp.com/channels/702230714585710602/702232127755780197/779682737917001758
Re-enable escape and tab on CM_Inputbox and CM_Dialogbox
Fix random blocks changing direction as the dragged container is never cleared so when it gets reused somewhere it will get updated when you press directions as if you were still dragging see https://discordapp.com/channels/702230714585710602/702232127755780197/779738549251080203 …

Bug fix train has arrived

---

Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeChromaPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLaserSpeedInterpolationPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLightingPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeStepGradientPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGeneratorPass.cs

Moved prop id splitting up to the main function as otherwise we delete all other prop notes nearby
Also fixes prop notes not being visible if spawned while propagation editing is enabled but not their event type

Split prop ids when running strobe gen

---

Assets/Locales/Options Shared Data.asset
Assets/Locales/Options_en.asset
Assets/__Scenes/03_Mapper.unity
Assets/__Scenes/04_Options.unity
Assets/__Scripts/MapEditor/UI/Node Editor/NodeEditorController.cs
Assets/__Scripts/PluginLoader/Plugin.cs
Assets/__Scripts/Settings/Settings.cs

Add text/ui size node editor settings, clean up ui
Also fixed editing off-screen objects (largely by deleting unneeded code)
By default:
With settings changed by user:

Node editor customisation & fixes

---

Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Notes/BeatmapNoteContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs
Assets/__Scripts/MapEditor/Grid/Collections/NotesContainer.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

So after hours of confusion and actually stepping through the source code for SortedSet<T> I learned that for delete to function as expected the items must still be sorted in the same way as when they were added to the set. This means any time we want to change the _time property of an object we need to re-add it to the set otherwise there's a chance when the tree is traversed later it won't work.
https://ideone.com/wpLvu3
On a new map place a single block
Place a second block later in time
Drag or shift move the second block before the first in time
Delete the second block
Save and exit
Reload the map
Observe the second block has not been deleted
----
At the time time I realised that if you move a note to a precision where _time will have more decimal places than the current selected …

Fix notes not deleting properly after being moved in time

---

Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs

Couple of performance optimisations for copying events and notes as they are most common to spam
Big boost in strobe gen on high event count maps by using the sorted set to exclude objects before and after the selected region.

Strobe gen go brrrr

---

Assets/__Scripts/MapEditor/AutoSaveController.cs

Autosave cleanup was always deleting the most recent autosave as even though we created an ordered list we never used it

Fix errors during autosave clean

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/Detection/BeatmapObjectCallbackController.cs
Assets/__Scripts/MapEditor/Detection/DingOnNotePassingGrid.cs
Assets/__Scripts/MapEditor/Grid/Collections/BeatmapObjectContainerCollection.cs
Assets/__Scripts/MapEditor/Hit Sounds/AudioUtil.cs

Basically moves the point at which are processed 0.5 seconds before they hit the play head and then adds a delay before they are played in the call to unity's audio system
Plus some handling for the notes between now and 0.5s time when pressing play and making sure things don't play after you stop

Schedule hit sounds instead of playing during frames

---

Assets/__Scripts/Map/BeatSaberMap.cs

Struggled to delete a bpm change in my test map while testing some other stuff as we don't touch the map file if we have no items in these lists even if there used to be.

Allow deleting last bpm change, bookmark, custom event

---

Assets/_Prefabs/MapEditor/Platforms/KDA.prefab
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs
Assets/__Scripts/Platforms/LightingEvent.cs
Assets/__Scripts/Platforms/LightsManager.cs

I missed a spot in gradient gen
Add light id offset because KDA sticks can't be re-ordered sensibly in prop id mode due to groupings between the chevron / lane lights and random sticks. But we can adjust the light id order.

Light id changes / fixes

---

Assets/__Scripts/Extensions/TransformExtensions.cs
Assets/__Scripts/Extensions/TransformExtensions.cs.meta
Assets/__Scripts/MapEditor/Mapping/Selection/BoxSelectionPlacementController.cs

Transform bounds correctly when rotated into the co-ordinate space we use for selection, this was preventing (or sometimes allowing) the selection box getting to objects in the map

Fix selection in 360

---

Assets/_Prefabs/UI/Strobe Gen Pass Panel.prefab
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeChromaPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLaserSpeedInterpolationPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLightingPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeStepGradientPass.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGenerator.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/StrobeGeneratorPass.cs
Assets/__Scripts/MapEditor/UI/Strobe Generator/Passes/ChromaStepGradientPassUI.cs

Made it way easier to scroll in the strobe generator UI by forwarding events down, adding an invisible background and increasing scroll speed.
Easings include all the normal tweens plus a flicker (first / last / first / last) and random (examples below)
Fixed a bug with nullable prop id not being checked and used prop mode instead
Should include fix for UI mirror button not working

Add chroma step gradient easings including two custom easings

---

Assets/_Prefabs/MapEditor/Platforms/Rocket.prefab
Assets/__Scenes/03_Mapper.unity
Assets/__Scenes/04_Options.unity
Assets/__Scripts/BeatSaberSong.cs
Assets/__Scripts/Input/Master.cs
Assets/__Scripts/Input/Master.inputactions
Assets/__Scripts/MapEditor/Grid/Collections/EventsContainer.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
Assets/__Scripts/MapEditor/UI/LaserSpeedController.cs
Assets/__Scripts/MapEditor/UI/SpectrogramSideSwapper.cs
Assets/__Scripts/Platforms/Track Rings/TrackLaneRing.cs
Assets/__Scripts/Platforms/Track Rings/TrackLaneRingsRotationEffect.cs
Assets/__Scripts/UI/Options/OptionsController.cs

- Moved/Added the following:
- Precision placement toggle `Q`
- Reset rings `Numpad 0`
- Camera attach to note grid `Ctrl+R`
- Leave options menu `Escape`
- Fixed rocket center prop id order
- Add chroma suggestion for environment removal, could bump this to a requirement?
- Fixed offset precision placement
- Removed waveform follows workflow option

Keybind rejig + assorted other changes

---

Assets/Locales/Options Shared Data.asset
Assets/Locales/Options_en.asset
Assets/__Scenes/04_Options.unity
Assets/__Scripts/Settings/Settings.cs
Assets/__Scripts/UI/Options/BetterSlider.cs
Assets/__Scripts/UI/PersistentUI.cs

Requires editor restart after changing.
Down to 256 seems to work fine for me, but having it as an options allows people with different hardware to try different options out. Don't know if this should remain an option of if we can just pick a lower number going forward.

Add experimental dsp buffer size option to allow reducing audio latency

---

Assets/Tests/Util/TestUtils.cs
Assets/__Scripts/Platforms/LightsManager.cs

WaitForEndOfFrame hangs forever in batch tests, null gets run slightly earlier in the loop but it seems to load the lights fine.
Any thoughts if this could have any other side effects?

Add logging around failing test

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs

I'm not super confident with what's going on in this method but it seems like using the time ratios will approach 1 as the current time tends towards infinity. This means for large time values their distance from 1 will never be >= smoothDeltaTime. This is bad as it means we can de-sync and never correct for it. I _think_ most of this desync in the map I'm testing is caused as playback starts (putting events into the queue, finding the current lighting state etc.) so if we can trigger a single correction this is all we need.
I think this may also be related to the skipping issue some people have reported and while I can't really reproduce it I hope this may improve that behaviour.
I've also replaced the usage of songAudioSource.time with timeSamples, this is marginally more accurate and …

My attempt at fixing audio sync late into songs

---

Assets/__Scripts/UI/SongInfoEditUI.cs

This just makes it so `.wav` actually gets loaded

Include wav support

---

Assets/__Scripts/Input/Master.cs
Assets/__Scripts/Input/Master.inputactions
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs

Adds three new keybinds, one for left rotations one for right (E and Q by default), as well as a modifier (Shift by default). These keybinds are for inserting/replacing rotation events at the current location in the song. The modifier keybind is used to switch between late and early rotation events. Currently only supports base game rotation events in increments of 15 degrees. Feel free to change the default keybinds, E/Q just made the most sense but not sure if there are plans to put something else on those buttons.

Added rotate in place keybinds

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/MapEditor/Audio/AudioManager.cs
Assets/__Scripts/MapEditor/Audio/SpectrogramChunk.cs
Assets/__Scripts/MapEditor/Grid/Collections/CustomEventsContainer.cs
Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs
Assets/__Scripts/MapEditor/Input/BeatmapNoteInputController.cs
Assets/__Scripts/MapEditor/Mapping/KeybindsController.cs
Assets/__Scripts/MapEditor/Mapping/LegacyNotesConverter.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BombPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ObstaclePlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Assets/__Scripts/MapEditor/UI/Chroma/PaintSelectedObjects.cs

Fix inconsistent grid visibility in hide grid mode
Add another digit to stop stretching between spectro chunks
Allow most inputs when mouse is outside window (placement is blacklisted as I assume that's why it was originally disabled?)
Add helper for safely accessing object customdata
Add more defensive coding around lightid editing
Try and fix errors from spectro generation again

Various improvements

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs

Using smoothDeltaTime I think? that at higher framerates the sync threshold gets smaller.
This just adds a lower bound of 0.04s so that any sync better than that won't trigger a resync even if that means more total frames are wrong.

Add lower bound to resync trigger to prevent lots of syncs happening at high framerates

---

Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLaserSpeedInterpolationPass.cs

Will not use _preciseSpeed if decimalPreciseSpeed is a whole number. Will also change _value to the whole number closest to decimalPreciseSpeed (unless that number is 0, in which case 1 will get used).
I changed one line and added another, probably badly, you're welcome.

Only use _preciseSpeed when necessary

---

Assets/__Scripts/UI/PreviewSong.cs

Currently, this is how the preview sounds like:
Now, it looks like this:

More accurate audio preview

---

Assets/__Scripts/PluginLoader/PluginLoader.cs

Fix plugin loading when paths contain unicode characters
Test code from a plugin:
```
Debug.Log(Assembly.GetCallingAssembly().Location);
Debug.Log(Assembly.GetExecutingAssembly().Location);
```
Old behaviour
```
C:\Users\micro\Downloads\姚明\chromapper\ChroMapper_Data\Managed\Main.dll
C:\Users\micro\Downloads\??\chromapper\Plugins\ErrorChecker\ErrorChecker.dll
```
New behaviour
```
C:\Users\micro\Downloads\姚明\chromapper\ChroMapper_Data\Managed\Main.dll
C:\Users\micro\Downloads\姚明\chromapper\Plugins\ErrorChecker\ErrorChecker.dll
```

Fix plugin loading with unicode paths

---

Assets/__Scripts/MapEditor/CameraController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/EventPlacement.cs
Assets/__Scripts/UI/LightshowController.cs

Maybe LockedOntoNoteGrid should be re-enabled when exiting lightshow mode. But this restores the behaviour before it was broken by changing the default value.
Also allowed fade/flash to be placed in all lights lane while in prop mode

Make aalto happy

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs

Wouldn't have thought this would do much but some dependency chain here meant that AudioClips were kept in memory.
Should reduce memory buildup if you load multiple maps in CM

Allow audio clip to be released when ATSC is destroyed

---

Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs
Assets/__Scripts/Platforms/PlatformDescriptor.cs
Assets/__Scripts/Platforms/RotatingLights.cs
Assets/__Scripts/Platforms/RotatingLightsBase.cs
Assets/__Scripts/Platforms/RotatingLightsLP.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs

- Middle click to invert boost lights
Just QOL change per https://discord.com/channels/702230714585710602/702231982335197264/797983545276628993
- Fix #277 by passing the event type to invert rotation direction (this is what will conflict with interscope)
- Save song before diff if needed
Previously if you created a new map and then created and saved a diff before saving the map it would throw an error, now it just saves the blank map (without any changes in the UI) first.

More tweeks

---

Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySettings.cs
Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs
Assets/__Scripts/UI/SongInfoEditUI.cs

I realised that I was constructing a Lazy and then immediately calling a method that tries to access its value. The idea was that even though we need to load the diff file to get the new env enhancements that we wouldn't load diffs unless we needed to display this data.
Changed it so that instead a null value is used internally to denote no change has been made. The map will be loaded and value populated when the diff is selected (this could further be optimised so that it only loads when showing the enhancements tab).
Also changed the "Open Editor" button so that it pulls from the lazy value.
Combined this means that for a full spread instead of loading diff files 6 (every diff on screen + one of them twice) times before you get to the editor we now load 1 time (or as many as you click …

Be lazier loading diffs

---

Assets/__Scripts/Intersections/Implementations/Internal.cs
Assets/__Scripts/Intersections/Implementations/Raycast.cs
Assets/__Scripts/Intersections/Intersections.cs
Assets/__Scripts/Map/Obstacles/BeatmapObstacleContainer.cs
Assets/__Scripts/MapEditor/CameraPositionToChunk.cs
Assets/__Scripts/MapEditor/Input/BeatmapInputController.cs

I was having some problems with selecting notes and events.
There are three modes depending on camera direction sadly the forward and backwards modes don't consider high FOV values so objects at the edge of the window that are "behind" the camera can't be selected.
The alternating mode works reasonably well in the middle of a map but at the start it would stop processing as soon as it considered a chunk before 0 so if the camera is over chunk 0 it checks 0, 1, -1, 2 -> stop. Because alternating has reached -1 objects in 3 or higher are inaccessible.
Just removed the forward/backward modes as high fov sadly makes them useless. We always alternate.
Code for getting the next group id simplified (I can't even read the old code)
We always do enough loops to reach the end in the furthest …

Raycasting fixes

---

Assets/_Graphics/Shaders/Editor/Instanced Toon Outline.shader
Assets/__Scripts/Map/BeatmapObjectContainer.cs
Assets/__Scripts/Map/Obstacles/BeatmapObstacleContainer.cs

Normally when scaling objects the toon shader's outline also scales however we use scale for walls to make them longer and it's not really intended that this would cause the selection to extend further.
To prevent this I've added an extra shader property that causes the shader to scale back to keep the outline the same size in world space. It's gated because apparently the process of reversing the scale is costly so it's set up to only be applied to walls.
VS now:

Add option to outline shader to offset mesh scaling

---

Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Input/Master.cs
Assets/__Scripts/Input/Master.inputactions
Assets/__Scripts/MapEditor/Hit Sounds/HitSoundVolumeController.cs
Assets/__Scripts/MapEditor/Hit Sounds/HitSoundVolumeController.cs.meta

Adds a keybind to mute/unmute hitsounds. Current (temporary) default binding is Alt+F1, but I'm open to suggestions.
Toggling hitsounds during playback will have a small delay due to hitsounds being scheduled ahead of time. This could potentially be solved by canceling and rescheduling all hitsounds, or by attempting to change their volume after scheduling, but the issue may be considered minor enough to not worry about.

add keybind to toggle-mute hitsounds

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
Assets/__Scripts/MapEditor/Grid/Collections/BPMChangesContainer.cs
Assets/__Scripts/MapEditor/Input/BeatmapBPMChangeInputController.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/BPMChangePlacement.cs

Makes the cursor follow the grid on BPM change tweak (Alt+scroll), makes BPM change placement default to the previous BPM, and improves scrolling behavior around BPM changes.
About moving cursor on BPM change tweak:
- Only applies on BPM tweak
- Does not affect undo/redo
- Does not affect other means of editing BPM changes
The reasoning for this is as follows:
- The main use is in mapping BPM slides, where you are likely to use BPM tweak
- Always moving cursor when a BPM change is added or modified would be inconsistent with the behavior of map objects (notes, lights, etc.) which remain stationary
- Moving the cursor on undo/redo would require the above, unless a new action type was created specifically for BPM tweak
- Desired behavior of undo/redo becomes less clear when the cursor is …

BPM change improvements

---

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs

If the event grid or track is clicked through the note grid (or vice versa but that's much harder to do) an event is placed when it shouldn't be. This can happen without the mapper noticing and cause a lot of misplaced events. This PR fixes that by simply checking if instantiatedContainer is active before calling ApplyToMap.

Placement bug fix

---

Assets/Locales/Options Shared Data.asset
Assets/Locales/Options_da.asset
Assets/Locales/Options_de.asset
Assets/Locales/Options_en-OWO.asset
Assets/Locales/Options_en-PT.asset
Assets/Locales/Options_en.asset
Assets/Locales/Options_es-ES.asset
Assets/Locales/Options_et.asset
Assets/Locales/Options_fi.asset
Assets/Locales/Options_fr.asset
Assets/Locales/Options_ja.asset
Assets/Locales/Options_nl.asset
Assets/Locales/Options_ru.asset
Assets/Locales/Options_sv-SE.asset
Assets/__Scenes/04_Options.unity
Assets/__Scripts/MapEditor/Audio/MetronomeHandler.cs
Assets/__Scripts/MapEditor/AudioTimeSyncController.cs
Assets/__Scripts/MapEditor/Detection/BeatmapObjectCallbackController.cs
Assets/__Scripts/MapEditor/Detection/DingOnNotePassingGrid.cs
Assets/__Scripts/Settings/Settings.cs

Adds a setting that compensates for audio latency by offsetting all visuals during playback.
AudioTimeSyncController keeps CurrentSeconds (and CurrentBeat) offset, and has new properties CurrentSongSeconds and CurrentSongBeats to expose precise audio timing, which are used by hitsounds and the metronome.

add audio latency compensation setting

---

Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
Assets/Locales/Options Shared Data.asset
Assets/Locales/Options_da.asset
Assets/Locales/Options_de.asset
Assets/Locales/Options_en-OWO.asset
Assets/Locales/Options_en-PT.asset
Assets/Locales/Options_en.asset
Assets/Locales/Options_es-ES.asset
Assets/Locales/Options_et.asset
Assets/Locales/Options_fi.asset
Assets/Locales/Options_fr.asset
Assets/Locales/Options_ja.asset
Assets/Locales/Options_nl.asset
Assets/Locales/Options_ru.asset
Assets/Locales/Options_sv-SE.asset
Assets/_Graphics/Materials/Grids/Base.mat
Assets/_Graphics/Materials/Grids/BaseTransparent.mat
Assets/_Graphics/Materials/Grids/BaseTransparent.mat.meta
Assets/_Graphics/Materials/Grids/LaneGrid.mat
Assets/_Graphics/Materials/Grids/One.mat
Assets/_Graphics/Materials/Grids/OneEight.mat
Assets/_Graphics/Materials/Grids/OneFourth.mat
Assets/_Prefabs/MapEditor/Prefab Materials/_Shaders/UnlitTransparentColored.shader
Assets/_Prefabs/MapEditor/Prefab Materials/_Shaders/UnlitTransparentColored.shader.meta
Assets/_Prefabs/UI/Settings/Options Tab.prefab
Assets/__Scenes/03_Mapper.unity
Assets/__Scenes/04_Options.unity
Assets/__Scripts/MapEditor/Grid/GridRenderingController.cs
Assets/__Scripts/Settings/Settings.cs

Adds a slider to make track backgrounds transparent/invisible
This is done by essentially leaving the grids in "high contrast mode" by disabling the other method of high contrast mode and leaving the base alpha of the grid layer at 0. The base layer of the tracks is then set to either the normal or high contrast color, and if the transparency slider is set above 0%, the shader is replaced with a transparent unlit color shader from [here](https://gist.github.com/keijiro/1681052)
A few tweaks had to be made to make this work, mostly just changing the high contrast system and moving the 1/4 grid under the waveform down a little bit because the rendering order had to be changed to match the new track base, which had to match the lasers.
I hope I committed all the correct files, Unity was …

Add transparent track backgrounds

---

Assets/__Scripts/MapEditor/Grid/Tracks/Track.cs

Fixes an elusive bug that's been around for a while where under some conditions the note track could become persistently slightly offset causing notes to become transparent when they shouldn't.

fix accumulating floating point errors on track z-position

---

Assets/Plugins/x86_64/discord_game_sdk.bundle.meta
Assets/Plugins/x86_64/discord_game_sdk.dylib.meta
Assets/Plugins/x86_64/discord_game_sdk.so.meta
Assets/StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle.meta

The unity version we upgraded to has support for apple silicon on OSX however native OSX libraries were set to Intel only. They _probably_ don't work on apple silicon but unity decided to stop bundling them in our build and in ~30 seconds of googling I couldn't find a way to setup SimpleEditorUtils to build an Intel specific version so instead I marked all the libraries as any cpu so at least the build works on Intel macs rather than none.

Set native libraries to Any CPU on OSX

---

Assets/__Scripts/FileOperationAPIWrapper.cs

Functionality depends on glib2, which should be widely available in linux distros. In case it's not available, it falls back on the regular delete.

add moving to trash capability on linux

---

Assets/__Scripts/UI/CM_InputBox.cs

This issue occurs when repeatedly placing bookmarks. The input box doesn't get selected even though the method is called.
I'm assuming this happens because the same game object is selected twice in a row, resulting in the events not being sent properly.
A working solution seems to be to set the selected game object to null first.

fix input fields in dialog boxes sometimes not being selected properly

---

Assets/_Graphics/Shaders/Editor/Note.shader
Assets/_Graphics/Shaders/Editor/Obstacle.shader
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/Map/Obstacles/BeatmapObstacleContainer.cs
Assets/__Scripts/Map/SpawnParameterHelper.cs
Assets/__Scripts/Map/SpawnParameterHelper.cs.meta
Assets/__Scripts/MapEditor/CameraController.cs
Assets/__Scripts/MapEditor/Detection/BeatmapObjectCallbackController.cs
Assets/__Scripts/MapEditor/UI/UIMode.cs
Assets/__Scripts/UI/MapEditorUI.cs
Assets/__Scripts/UI/SongEditMenu/DifficultyInfo.cs

- Fixes the crouch keybind in playing mode (defaults to S)
- Saves and restores the camera position when going in and out of playing mode
- Fixes the spawn offset calculation (and moved HJD calculation code to helper class)
- Shows the song timeline when paused (in playing and preview modes)
- UI fade transition times reduced to 0.2 seconds (from 1 second)
- Disables grid line on the surface of notes when the placement grid is not visible
- Obstacle fade distance during playback now follows the spawn offset for notes
- Camera z-position tweaked in playing mode (from -7 to -6)

improvements to the "playing" ui mode (and some other things)

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs

I return once more to repent for my sins.
This still isn't ideal behavior since the grid visibly jumps around in time, but it doesn't seem to actually cause things to break.
Ideally you would apply playback speed changes only after some time has passed (equal to the amount of compensation) but that would be a lot more difficult to implement.

account for playback speed when using audio latency compensation

---

Assets/__Scripts/UI/SongSelectMenu/SongListItem.cs

Fix song duration cache not being written to due to coroutines being stopped while scrolling
Fix issue where if songlistitem has never been initialised (if the user has no maps) updating the duration throws an error

Fix song cache issues

---

Assets/__Scripts/MapEditor/EditorScaleController.cs

This fixes an annoying bug I've been chasing for a while where for seemingly no reason I was placing notes slightly off-grid.
EditorScaleController calls `atsc.MoveToTimeInSeconds`, changing this to `MoveToTimeInBeats` avoids introducing floating point errors.

fix floating point errors introduced to atsc.CurrentBeat when changing editor scale

---

Assets/__Scripts/UI/SongEditMenu/EnvEnhancement.cs

Apparently `_lightID` and `_lightId` both work, so using `_lightId` because that's what documentation says.

Don't yeet lightId from env enhancements

---

Assets/__Scripts/Platforms/PlatformDescriptor.cs

In BS 1.21.0 (maybe 1.20.0 as well), inverted colors now respect boost colors.

Inverted colors now respect boost lights

---

Assets/Input/Master.cs
Assets/Input/Master.inputactions

Some commits of walls have been merged. So I will add some introduction of what I've done for v3 obstacles.
- In v3 map, walls will display in v3 height(max at 4.2f). 
However, placement height is still using v2 height(3.5f). Therefore you will experience height difference between placing and placed. Currently I'm not certain about how should we make placement and we may not want to change 3.5f at everywhere, so temporarily keep it for a while..
- To change upper bound, use `shift + scroll`. To change lower bound, use `alt + shift + scroll`.
This is not intuitive for a v3 map wall placing. However, for v3 map, we need to know start height(range from [0, 2]) and height(range from [1, 5]). If we use three step placing(lower bound -> upper bound -> duration), then it is not in cosistent with …

Basic function of V3 Walls

---

Assets/Input/Master.cs
Assets/Input/Master.inputactions
Assets/Locales/Mapper Shared Data.asset
Assets/Locales/Mapper_en.asset
Assets/Locales/Options Shared Data.asset
Assets/Locales/Options_en.asset
Assets/__Scenes/03_Mapper.unity
Assets/__Scenes/04_Options.unity
Assets/__Scripts/Map/BeatSaberMap.cs
Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Events/BeatmapEventContainer.cs
Assets/__Scripts/Map/Events/EventAppearanceSO.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/Map/Events/MapEventV3.cs
Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs
Assets/__Scripts/MapEditor/Mapping/Strobe Generator/Passes/StrobeLightingPass.cs
Assets/__Scripts/MapEditor/UI/Strobe Generator/Passes/BasicStrobePassUI.cs
Assets/__Scripts/Platforms/LightingEvent.cs
Assets/__Scripts/Platforms/PlatformDescriptor.cs
Assets/__Scripts/Settings/Settings.cs

`Visualize Chroma Alpha` height accounts for both Chroma alpha and Vanilla floatValue. I don't see a big reason to have these as separate options. As such, I have renamed this option to `Visualize Event Alpha`.
Known behaviour
* Quick editing floatValue does not offset event base to account for height change 
* This is only done on actions which refresh like node editor or paint

Add floatValue support

---

Assets/__Scripts/Map/BeatSaberMapV3.cs
Assets/__Scripts/Map/BeatmapObject.cs
Assets/__Scripts/Map/Events/ColorBoostEvent.cs
Assets/__Scripts/Map/Events/MapEvent.cs
Assets/__Scripts/Map/Events/RotationEvent.cs
Assets/__Scripts/Map/Events/RotationEvent.cs.meta
Assets/__Scripts/MapEditor/Input/BeatmapEventInputController.cs

* Previews rotation
* Adds saving and conversion to and from V3
* Converting V3 rotation to V2 will use ME values if there is no vanilla value for the rotation amount
* Quick edit for V3 rotation increments in 1s
* Rotation events are not yet placed in V3 format
* I feel that would be better for a future PR that supports Boost and Rotation event placement in V3

Basic V3 rotation event support 

---

Assets/Locales/Mapper Shared Data.asset
Assets/Locales/Mapper_en.asset
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/AutoSaveController.cs
Assets/__Scripts/MapEditor/UI/PauseManager.cs
Assets/__Scripts/Settings/Settings.cs

Resolves (#398).
Adds dialogue prompt to remove objects outside the map on saving.
Setting is hidden because I don't know what use case you would have to disable it but someone is going to want to for whatever reason.

Prevent saving objects outside of map

---

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs

As far as I can tell this time assignment was entirely redundant as time already got assigned in the line above, and as a bonus it introduced floating point errors due to needlessly multiplying and dividing by editor scale

remove redundant time assignment when dragging objects

---

Assets/__Scripts/MapEditor/Audio/AudioManager.cs

previously only the right channel would be used
averaging waveform data isn't technically correct but it's cheap and good enough most of the time
scale factor of 1/1.5 seems to roughly match old behavior from brief testing

fix broken channel averaging for spectrogram generation

---

Assets/__Scripts/Beatmap/Base/BaseEvent.cs
Assets/__Scripts/Beatmap/Base/BaseGrid.cs
Assets/__Scripts/Beatmap/Base/BaseObject.cs
Assets/__Scripts/Beatmap/Base/BaseObstacle.cs
Assets/__Scripts/Beatmap/Base/BaseSlider.cs
Assets/__Scripts/Beatmap/V2/V2Event.cs
Assets/__Scripts/Beatmap/V2/V2Note.cs

Right now, neither the CustomData nodes nor the Custom* event properties are particularly authoritative, and the only way to fully remove them is to unset both. This PR makes the CustomData node authoritative, and will overwrite and unset properties on ParseCustom(). Going the other way would be much harder, because JSONNodes would need to be `Remove`d and non-events don't yet have Custom* properties.
Implementation note: the ternary is necessary because of JSONLazyCreator, if there was a 
```cs
public JSONNode? TryGet(string key)
```
this could look like
```cs
CustomLerpType = CustomData?.TryGet(CustomKeyLerpType)?.Value
```
~~force push was for commit signing, don't worry about it~~

Unset custom properties when CustomData nodes are removed

---

Assets/__Scripts/PluginLoader/PluginLoader.cs

Right now one incompatible plugin will cause all plugins to not run, even though they show up in the plugin list. This prevents that and puts a helpful message in the log.

Graceful plugin failure

---

Assets/__Scripts/Beatmap/Base/BaseObstacle.cs
Assets/__Scripts/Beatmap/Converters/V2ToV3.cs
Assets/__Scripts/Beatmap/Converters/V3ToV2.cs

obstacle is going to haunt me forever
context: everytime difficulty is saved, it goes through conversion process for v2 to v3 object in beatmap v3 and vice versa.
previously, it creates a copy of object and converts custom data along with it, but this is not necessary for matching version object and may cause confusion when custom data converts the old data and appearing in next save

Few fixes and minor optimisation

---

Assets/Input/Master.cs
Assets/Input/Master.inputactions
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/AutoSaveController.cs
Assets/__Scripts/MapEditor/MapExporter.cs
Assets/__Scripts/MapEditor/MapExporter.cs.meta
Assets/__Scripts/MapEditor/UI/PauseManager.cs
Assets/__Scripts/Singletons/Adb.cs
Assets/__Scripts/UI/SongInfoEditUI.cs
ChroMapper.sln

This PR refactors some of the export code to allow exporting to Quest in other menus, specifically the mapper editor. This has been something that many users including myself have wanted for some time. Finally got some time to implement this.
While I've tested this, I do want to get a bigger testing sample (as my previous feature implementations have lacked proper polish in the past...)
Additions:
- Button for exporting while in editor (pause menu)
- Shortcut for exporting
~~TODO: Hide export button in pause menu unless ADB is installed~~ - Done

Feat: Quest Export Buttons and shortcut

---

Assets/Editor/SimpleEditorUtils.cs

As discussed in #433, Unity exposes settings in the macOS version of the Editor, which allows applications to be built as a universal x64 and ARM application. This should theoretically allow ChroMapper to run on both Intel-based Macs *and* M1 macs without the need of Rosetta.

Export ChroMapper as a Universal macOS application

---

Assets/__Scripts/Beatmap/Base/BaseObstacle.cs

I looked through the rest of the `ParseCustom`s, this is the only one missed

Clear CustomSize when removed from CustomData

---

Assets/__Scripts/MapEditor/Grid/CreateEventTypeLabels.cs

Some people want this for ExtendedLightIDs

Fix lane labels when skipping LightIDs

---

Assets/__Scripts/Input/InputSystemPatch.cs
Assets/__Scripts/MapEditor/Graphics/Better Bloom/BetterBloomController.cs

This PR aims to restore ChroMapper compatibility on Apple Silicon devices by disabling its Harmony patches on macOS.
On current `dev`, this may lead to problematic behavior relating to the Input System, which relies heavily on its Input System patch. However, on `2021.3`, this Harmony patch may be less necessary. If needed, this PR can be re-targeted to `2021.3` and merged there.
Unfortunately, Better Bloom will be completely disabled on macOS, since Universal Render Pipeline still has no option to enable a full resolution bloom effect.
Also to note, Unity does not seem to define specific preprocessor symbols for M1 specifically, so these changes will apply to Intel based Apple devices as well, even though Harmony works just fine on Intel devices.

Disable Harmony patches on macOS

---

Assets/__Scripts/PluginLoader/Plugin.cs
Assets/__Scripts/PluginLoader/PluginLoader.cs

Does two things:
1. Keep loading plugins if one has an error.
2. Actually give useful exceptions for plugins instead of just a `TargetInvocationException`.

Better Plugin Debuging

---

Assets/Input/Master.cs
Assets/Input/Master.inputactions
Assets/__Scripts/MapEditor/Grid/Collections/ChainGridContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/CustomEventGridContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/NoteGridContainer.cs
Assets/__Scripts/MapEditor/Grid/Collections/ObstacleGridContainer.cs
Assets/__Scripts/MapEditor/UI/UIMode.cs

This adds multiple new keybindings for changing the current UIMode of the editor as well as changes the current `Ctrl + H` keybinding.
Keybindings Changes:
- Toggle UI Mode: `Ctrl + E`
- Toggle UI Mode (Reverse): `Ctrl + Q`
- Toggle UI Mode (Normal): `Ctrl + 1`
- Toggle UI Mode (Hide UI): `Ctrl + 2`
- Toggle UI Mode (Hide Grids): `Ctrl + 3`
- Toggle UI Mode (Preview): `Ctrl + 4`
- Toggle UI Mode (Playing): `Ctrl + 5`
Video showing the changes:
https://github.com/Caeden117/ChroMapper/assets/40338395/a2f76592-5302-4ba8-8bc9-cbffe223430a

Add more keybinds for changing UIMode

---

Assets/__Scripts/MapEditor/MapExporter.cs
Assets/__Scripts/OSTools.cs
Assets/__Scripts/OSTools.cs.meta
Assets/__Scripts/UI/DevConsole.cs
Assets/__Scripts/UI/Options/OptionsController.cs

Uses the same behavior as MapExporter and OptionsController.
*This should probably be made into a helper function somewhere if you have a good place to put it.*

Fix the open config folder button on Linux

---

Assets/__Scripts/Beatmap/Appearances/GeometryAppearanceSO.cs
Assets/__Scripts/Platforms/LightsManager.cs

Fixes an issue where all geometry-added light ids are grouped under propid 1
Example:

Exclude geometry lights from propid

---

Assets/__Scripts/UI/DevConsole.cs
Assets/__Scripts/UI/LogLineUI.cs

Our current text hosting service [paste.ee](https://paste.ee) has been unreliable as of late, with a period of downtime preventing CM bug reports from being generated, to browsers flagging paste.ee as a phishing site and causing distrust in users (and, to some extent, myself).
This PR removes paste.ee as the host for bug reports. ChroMapper will generate all bug reports on the local file system, in a `Bug Reports` subfolder in persistent data. When generating a bug report, ChroMapper will now open OS's file explorer instead of the web browser.

Local Bug Reports

---

Assets/Tests/ContainerCollectionTest.cs
Assets/Tests/NotesContainerTest.cs
Assets/Tests/SimpleMirrorTest.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/ActionCollectionAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedCollectionAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedCollectionAction.cs.meta
Assets/__Scripts/BeatmapActions/BeatmapAction.cs
Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs
Assets/__Scripts/MapEditor/UI/MirrorSelection.cs

Add `BeatmapObjectModifiedCollectionAction` which deletes all objects *and then* adds all objects on undo/redo instead of performing sequential undo/redo (which does delete -> add -> delete -> add) in `ActionCollectionAction`.
This fixes some ghost/stacked objects issues that have been appeared.

Fix ghost/stacked objects caused by group modified actions 

---

ProjectSettings/ProjectSettings.asset

The current (Unity default) app category causes macOS to enter game mode when the app is put in full screen, which is not ideal for energy purposes. I am doing a broader investigation of the program preventing sleep and if it's possible to avoid, but this change is still relevant for energy use reduction.
Game mode is controlled by having one of the `game`-related tags set in Mac App Store Options/Category field in Unity. (Maps to `LSApplicationCategoryType`) I've changed it to `developer-tools` but `utilities` could also fit.
Note: Game Mode will still activate when you run the built project on a Mac if Unity Hub is running. This doesn't appear to be the case when it is closed, or sent to a computer without Unity Hub installed.
https://developer.apple.com/forums/thread/739387 …

[macOS] Change App Category to Prevent Game Mode

---

Assets/__Scripts/Beatmap/Base/BaseDifficulty.cs

when converting bpm changes, bookmark times are already updated, so we should set the CustomData key to indicate it

bookmarks no longer get times double-converted

---

Assets/__Scripts/Beatmap/Info/Base/BaseInfo.cs

the modified date of the containing directory only changes when new files are written
instead we can use the modified date of Info.dat directly, which is updated whenever the map is saved

sort maps in songlist based on modified date of Info.dat

---

Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedAction.cs

grid was getting refreshed before future object positions were refreshed, while it should happen after
bpm event spawn/delete already does this so we don't need to do it there

grid properly updates on undo/redo of bpm event tweak

---

Assets/TestsEditMode/BeatmapV2Test.cs
Assets/TestsEditMode/BeatmapV3Test.cs
Assets/TestsEditMode/BeatmapVersionSwitchingTest.cs
Assets/TestsEditMode/InfoTest.cs
Assets/__Scripts/Beatmap/Info/Base/BaseInfo.cs
Assets/__Scripts/Beatmap/Info/V2/V2Info.cs
Assets/__Scripts/Beatmap/Info/V4/V4Info.cs
Assets/__Scripts/Beatmap/V2/V2Difficulty.cs
Assets/__Scripts/Beatmap/V3/V3Difficulty.cs
Assets/__Scripts/MapEditor/AutoSaveController.cs
Assets/__Scripts/Requirements/ChromaReq.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySelect.cs
Assets/__Scripts/UI/SongEditMenu/DifficultySettings.cs

fixes converted custom bpm changes not being deleted, among other potential similar issues
(now also on Info.dat, fixing issues with removing contributors as one example)
(now also fixed diff label not being copied to new diff, among some other properties)

remove known and parsed customData from base CustomData object

---

Assets/__Scripts/Beatmap/Containers/NJSEventContainer.cs

the actual NJS value on these is irrelevant, and this makes them visually distinct

hide text on NJS extend events

---

Assets/__Scripts/MapEditor/Mapping/PlacementControllers/NotePlacement.cs

big quality of life change when working with arcs attached at different direction from note

don't update slider direction when dragging note until note direction is changed

---

Assets/__Scripts/MapEditor/UI/NoteLanesController.cs

lane count is always set to 4 on load, but the setting wasn't updated so it kept the previous value

update note lane count setting on map load

---

Assets/__Scripts/MapEditor/AudioTimeSyncController.cs

this greatly mitigates accumulating floating point errors from scrolling
though they can still occur if you scroll while not being on-grid at your current precision

resnap to grid on scroll if we were already snapped

---

Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectDeletionAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectModifiedWithConflictingAction.cs
Assets/__Scripts/BeatmapActions/Beatmap Actions/BeatmapObjectPlacementAction.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/PlacementController.cs

fixes the conflicting object not reappearing immediately upon undo, but only after the next action that refreshes the pool
(now also fixes ghost object issues with undo/redo)
(now also fixes undo of multiple conflicting objects on object modified with conflicting action)

fixes related to undo/redo with conflicting objects

---

Assets/__Scripts/MapEditor/Mapping/Selection/SelectionController.cs

The current logic leads to some weird behavior with ExtendedLightIDs, those being:
1. As noted in [here](https://discord.com/channels/702230714585710602/1316860775108972644), being unable to shift to id's without previewed lights, and
2. It doesn't skip light ids that should be skipped, eg are not referenced by and events, geometry or environment enhancements:
https://github.com/user-attachments/assets/dcdcbfc5-7060-4563-a46f-6b07993907af
This fixes both issues by shifting based on lane position instead.

Shift lightIDs based on lanes, not max light id

---

.github/workflows/release-post.yml

This PR adds a GitHub Actions workflow to ChroMapper which sends a curl request to [Jenkins](https://jenkins.kirkstall.top-cat.me/job/ChroMapper/) to automatically promote the latest version of Dev to Stable.
The endpoint URL and authorization token are stored as secrets which I will store in the repository.

Automatically promote Dev builds to Stable on Release

---

Assets/__Scripts/PluginLoader/Plugin.cs
Assets/__Scripts/PluginLoader/PluginLoader.cs
Assets/__Scripts/UI/DevConsole.cs

**This change applies STRICTLY to exceptions that occur from plugins.** 
Such exceptions are logged normally with an extra line above stating the plugins name that's causing the exception to occur, giving users a guide to proceed with the error.

Log originating plugins when exceptions occur

---

Assets/Locales/Mapper Shared Data.asset
Assets/Locales/Mapper_en.asset
Assets/_Graphics/Textures And Sprites/SVGs/mapping-arc.svg
Assets/_Graphics/Textures And Sprites/SVGs/mapping-arc.svg.meta
Assets/_Graphics/Textures And Sprites/SVGs/mapping-chain.svg
Assets/_Graphics/Textures And Sprites/SVGs/mapping-chain.svg.meta
Assets/__Scenes/03_Mapper.unity
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ArcPlacement.cs
Assets/__Scripts/MapEditor/Mapping/PlacementControllers/ChainPlacement.cs
Assets/__Scripts/MapEditor/UI/Placement Controller UI/PlacementModeController.cs

This way arc and chains aren't almost impossible to figure out how to use naturally. These buttons aren't really a placement "mode" like the rest but it's better than nothing and next dev is probably a good time for general cleanup.

Add arc and chain buttons to editor bar
